### PR TITLE
docs: add useful many-to-many query examples

### PR DESCRIPTION
**Pull request by PedroBern**
### Description

Add some useful many-to-many query examples to the docs.

[live preview shortcut](https://deploy-preview-6099--hasura-docs.netlify.app/graphql/core/queries/query-filters.html#filter-many-to-many-relationships)

Filtering many-to-many relationships isn't as intuitive as filtering array or object relationships, and I have found that the docs is missing some basic examples.

Essentially I added 4 new examples:

- [x] Filter articles containing at least some specific tags
- [x] Filter articles not containing some specific tags
- [x] Filter articles containing at least some specific tags AND not containing other tags
- [x] Filter articles containing an exact combination of tags, no more, no less

I'm available to make changes to the PR if necessary :)

---

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Docs

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No

#### Metadata

Does this PR add a new Metadata feature?
- [x] No

#### GraphQL
- [x] No new GraphQL schema is generated

#### Breaking changes

- [x] No Breaking changes

### CODE REVIEW

**Review by divyabhushan — APPROVED** [review]

**Review by divyabhushan — APPROVED** [review]

**Comment by divyabhushan** [comment]
Moving the [PR](https://github.com/hasura/graphql-engine-mono/pull/3644) to `graphql-engine-mono` repo including the latest docs structure and content.

**Review by divyabhushan — APPROVED** [review]
#https://github.com/hasura/graphql-engine-mono/pull/3644

**Comment by Stefmore02** [comment]
Closing again as these are `.rst` and not `.mdx` docs. If you can port them over to `.mdx `please feel free to open a new PR.

**Pull request closed without merging**
