### PR TITLE
Docs: add advanced example on aggregates (close #2987)

### LINKED ISSUE #2987: Add advanced example for aggregation queries
The examples we have here: https://docs.hasura.io/1.0/graphql/manual/queries/aggregation-queries.html#aggregation-queries are quite basic.

We can add a more advanced example here.

### PR DESCRIPTION
**Pull request by wdtamagi**
### Affected components 

- Docs

### Related Issues

#2987

### CODE REVIEW

**Comment by marionschleifer** [comment]
@wdtamagi do you want to add something here? Otherwise we can close this PR.

**Comment by wdtamagi** [comment]
@marionschleifer I'm waiting for the list of things to do the examples. In the #2987 issue @coco98  suggested discussing with the team to see what you need.

**Comment by wdtamagi** [comment]
But we can close this PR and I can make a new one when I get more information.

**Comment by marionschleifer** [comment]
@wdtamagi no, in this case let's leave it open 🙂 I will make sure that an example is added until the end of the week.

**Pull request closed without merging**
