### PR TITLE
docs: restructure deployment section

### PR DESCRIPTION
**Pull request by marionschleifer**
### Description

This PR is based on a discussion earlier this year with Rikin & Rajoshi and solves some confusion in the deployment section of docs:

- Move deployment guides under `Deployment`
- Under deployment, make "Deploying", "Updating GraphQL engine" etc. title sections rather than "Heroku", "Docker" etc.

After this gets merged, we can close the [old restructuring PR](https://github.com/hasura/graphql-engine/pull/4328) that is very old and would have had too many conflicts.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Docs

### Affected section

https://deploy-preview-5339--hasura-docs.netlify.app/graphql/manual/deployment/index.html

### CODE REVIEW

**Comment by marionschleifer** [comment]
@sezgi @rikinsk please check out the new structure as discussed. The list of guides is duplicated in `deployment/index` and `deployment/deploying/index` but I think it can be useful to have it in both places. Please let me know if you can think of a better way of handling this.

**Comment by sezgi** [comment]
Tangential: we can search & replace `One-Click` with `One-click`

**Comment by marionschleifer** [comment]
@sezgi please see changes.

**Comment by sezgi** [comment]
Not sure why the sidebar still shows the old title. Caching issue?

Screen Shot 2020-07-20 at 7 04 16 PM

**Comment by marionschleifer** [comment]
@sezgi I had only changed it in the page title as I thought we can leave the navigation title as it was. However, I changed it now too for consistency.

**Pull request merged**
