### PR TITLE
docs: add guide on performance tuning (fix #4805)

### LINKED ISSUE #4805: docs: guide on performance tuning
In the `deployment` section of the docs, we should add a page on performance tuning.

We can use [this](https://github.com/hgiasac/blog-builder/blob/master/pages/posts/2020-05-15-Tuning-Hasura-at-Scale.md) for content. Thank you @hgiasac 🙏

### PR DESCRIPTION
**Pull request by aniketh-varma**
### Description
Added a Performance tuning page to the Deployment section of the Hasura docs as mentioned in #4805 

#### Long Changelog

The content for the page was mentioned in the issue, linked [here](https://github.com/hgiasac/blog-builder/blob/master/pages/posts/2020-05-15-Tuning-Hasura-at-Scale.md)

I have uploaded the images required for the page in the docs/static/img/deployment folder of the repository

### Related Issues

#4805 

### Solution and Design

Have added a new `.mdx` file named `performance-tuning.mdx` containing the contents of [this](https://github.com/hgiasac/blog-builder/blob/master/pages/posts/2020-05-15-Tuning-Hasura-at-Scale.md) file

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No

Does this PR add a new Metadata feature?
- [x] No

#### GraphQL
- [x] No new GraphQL schema is generated

#### Breaking changes

- [x] No Breaking changes

### CODE REVIEW

**Comment by robertjdominguez** [comment]
@aniketh-varma, thanks for opening this PR and transferring this information over 🔥 

Would you be willing to do a grammar pass over the document? There are numerous inconsistencies with subject / verb agreement and other grammatical issues. If so, let me know.

**Comment by aniketh-varma** [comment]
> @aniketh-varma, thanks for opening this PR and transferring this information over 🔥
> 
> Would you be willing to do a grammar pass over the document? There are numerous inconsistencies with subject / verb agreement and other grammatical issues. If so, let me know.

Sure @robertjdominguez! I will try to correct the grammatical mistakes I encounter.

**Comment by robertjdominguez** [comment]
Lovely! Just give me a ping here and I'll check back in to re-review 🤙

**Comment by robertjdominguez** [comment]
With this latest commit, are you ready for another review @aniketh-varma? 😄

**Comment by aniketh-varma** [comment]
Hi @robertjdominguez, I haven’t done all the changes yet. I will ping you here once my work is ready for a review :)

**Comment by aniketh-varma** [comment]
Hi @robertjdominguez, I have done the changes, and I am ready for another review :)

**Comment by robertjdominguez** [comment]
Thanks, @aniketh-varma! I hope to get to it tomorrow 🤞 

Back to you soon!

**Comment by robertjdominguez** [comment]
Great work, @aniketh-varma! I've done a pass over the updates you made. I've handed this over to our design team for them to update the ERDs (as what we had in there doesn't match our current design system). We appreciate this contribution and the time you put into it 🎉 

It will take them some time, so you may not see a merge for a bit 👍

**Comment by aniketh-varma** [comment]
Thanks for the review @robertjdominguez, request you to please add the hacktoberfest-accepted label to this PR, so that it can count towards my contributions.

**Comment by Stefmore02** [comment]
Hey! @aniketh-varma 

Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation and you will be getting an email with the swag form shortly.✨

**Comment by Stefmore02** [comment]
Closing this PR, since changes were merged [[6163](https://github.com/hasura/graphql-engine-mono/pull/6163)].

**Pull request closed without merging**
