### PR TITLE
console: append "IF NOT EXISTS" for adding and "IF EXISTS" for removing of columns (fix #5284)

### LINKED ISSUE #5284: Use ADD COLUMN "IF NOT EXISTS" when generating up migrations
Right now, the up migrations are not idempotent. This is one such example.

When adding a column, simply add it only if it doesn't exist, otherwise do nothing (= migration has already been run)

### PR DESCRIPTION
**Pull request by GrizliK1988**
console: append "IF NOT EXISTS" for adding and "IF EXISTS" for removing of columns (fix #5284)

### Description

Added
- "IF NOT EXISTS" to ALTER TABLE ADD COLUMN in up and down migrations
- "IF EXISTS" to ALTER TABLE DROP COLUMN in up and down migrations
This helps to avoid potential problem of failing a migration that adds or removes columns twice.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Console

### Related Issues
#5284

### Steps to test and verify
Unfortunately I wasn't able to make cypress catch an ajax call to /apis/migrate endpoint to verify the payload. To verify the fix manual testing is required.

### CODE REVIEW

**Comment by ItsWendell** [comment]
Simple but effective, nice work!

**Comment by GrizliK1988** [comment]
Thanks!

**Comment by GrizliK1988** [comment]
Good evening!

Could you please review this one?

**Review by beerose — APPROVED** [review]
Thanks for your PR!

Approving console changes.

**Comment by beerose** [comment]
Hi @GrizliK1988! Thanks again for your PR, however, we decided not to introduce independent migrations. You can check the details here: https://github.com/hasura/graphql-engine/issues/5284#issuecomment-731169068.

I'm closing your PR, and I hope to see more of your contributions in the future 😊

**Pull request closed without merging**
