### PR TITLE
Adding admin secret to the azure arm template (close #3612)

### LINKED ISSUE #3612: Feature request: Add admin secret parameter to azure template
It would be really great to have Hasura admin secret as a parameter when using azure arm template to one-click-deploy.

This is how I imagine it -

image

### PR DESCRIPTION
**Pull request by sushruth**
### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [x] Other (list it)

### Related Issues

#3612

### Solution and Design

Adding a parameter and a environment variable is fairly straight forward based on azure arm documentation. Diff explains it much better.

### Steps to test and verify

NA

### Server checklist

NA

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed
     

No breaking changes

### CODE REVIEW

**Comment by marionschleifer** [comment]
@sushruth thank you so much for your contribution 🙏 we'll review your PR soon and get back to you 🙂

**Comment by shahidhk** [comment]
@sushruth None of our getting started templates have admin secret added to them. This is for making it easy for people to try out Hasura and when they want to more to a production environment, they can easily edit the template or add required env vars from the settings. 

Will you add this as documentation to the README instead of editing the template directly?

**Comment by sushruth** [comment]
@shahidhk Sure! That sounds good too. Will do.

**Comment by shahidhk** [comment]
@sushruth Feel free to re-open the PR when you add the fix. Thanks a lot for your efforts :smile: 

I am closing this issue as a stale one.

**Pull request closed without merging**
