### PR TITLE
add business logic page to docs

### PR DESCRIPTION
**Pull request by rikinsk-zz**
### Affected components 

- Docs

### CODE REVIEW

**Comment by rikinsk** [comment]
We should also add a page under Mutations for doing **validations** with the following solutions:

- Postgres check constraints
- Event triggers: Insert with valid=false, run event trigger and set to true if valid, filter with valid=true
- Remote schema: use like a middleware. Make call to remote schema, validate, call HGE to do action  with permissions checks.

**Comment by mnlbox** [comment]
It's very useful.
@rikinsk Thanks man

**Comment by tirumaraiselvan** [comment]
Not a big fan of pre-CRUD/ post-CRUD terminologies. How about sync/async logic?

**Comment by hmexx** [comment]
> 
> 
> Not a big fan of pre-CRUD/ post-CRUD terminologies. How about sync/async logic?

Agree with @tirumaraiselvan . Sync/Async would be good as the top-level categorisation.

Other potential changes:

- Put Views within Synchronous instead of their own category.
- Add Postgres constraints checks within Synchronous (mention they are ideal for simple validation)
- Add Postgres native triggers to Asynchronous (this one is debatable as Event Triggers are better practice)

**Pull request closed without merging**
