### PR TITLE
infra: add check for images in docs (fixes #5853)

### LINKED ISSUE #5853: infra: add check for images in docs
### Motivation

As explained in [this guide](https://github.com/hasura/graphql-engine/wiki/How-to-write-docs-pages#images), we should compress images that are added as part of a docs pull request. This sometimes gets forgotten and then a PR gets merged with too large images.

### Instructions

We should make this part of the PR process. I've added a label called `docs-compress-images`. 

We should write a GitHub action that checks the following:

- Is it a docs PR?
- Has one or more images been added?

If the answer to both is yes, the build should only succeed if the label `docs-compress-images` is added. Otherwise it should fail.

### Reference

We have a similar (yet not exactly the same) [use case for the changelog label](https://github.com/hasura/graphql-engine/blob/master/.github/workflows/changelog.yml). You can check it out for inspiration.

### PR DESCRIPTION
**Pull request by Hard-Coder05**
### Description
I have added a github action to check wether a PR is made for doc and if an image file has been added, then docs-compress-images label is required.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.
### Affected components

- [x] Build System
- [x] Tests

### Related Issues

close #5853

### CODE REVIEW

**Comment by Hard-Coder05** [comment]
@marionschleifer @mehtavishwa30 I have made the PR. You can review it once and Suggest if any change is required!

**Comment by marionschleifer** [comment]
@Hard-Coder05 thank you for your PR 🙂 have you tested the Github action? If not, please test it by doing a mock change in docs and add an image to see if the image gets added. If we see that it works, we can remove these changes. Thanks!

**Comment by Hard-Coder05** [comment]
> @Hard-Coder05 thank you for your PR  have you tested the Github action? If not, please test it by doing a mock change in docs and add an image to see if the image gets added. If we see that it works, we can remove these changes. Thanks!

@marionschleifer Okay I am testing it out!

**Comment by marionschleifer** [comment]
@Hard-Coder05 seems like it's not working. All checks still pass. Please test thoroughly. Also, check in which folder the images / screenshots are actually added in docs and check for this specific folder on the Github action.

**Comment by Hard-Coder05** [comment]
@marionschleifer Please add `c/docs` label on this PR so that I can test it!

**Comment by Hard-Coder05** [comment]
@marionschleifer 
I have confirmed it. 
The test runs only if there is change in image files. Then it checks if its has `c/docs` label then it checks for the `docs-compress-images` label if present then passes else fails.
Now you can test it from your side even!

**Comment by Hard-Coder05** [comment]
@marionschleifer 
I guess you can merge the PR now as everything is working properly and close the issue!

**Comment by marionschleifer** [comment]
@Hard-Coder05 I just talked to the team. What we actually need in the Github action is not a check for the `docs` label, but a check in the docs folder to see if an image has been added. Because let's say someone adds an image but forgets to add the `docs` label, then the build will pass even though the other label is not added. Can you make this change? Then this will be ready go get merged 🙂

**Comment by Hard-Coder05** [comment]
@marionschleifer Okay I will work on it !

**Comment by Hard-Coder05** [comment]
@marionschleifer I have made the required change. The paths variable has been set to `docs/**/*.<file-extension>` . This will trigger the test only when an image is added in the docs file.
I took reference from https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
Screenshot from 2020-10-11 08-53-33

**Comment by marionschleifer** [comment]
@Hard-Coder05 I just tested this by adding an image in `docs` and I should get an error because the label isn't added. Can you please fix this and test it with an image?

**Comment by Hard-Coder05** [comment]
@marionschleifer I dont know what is going wrong! Could you please help me out? The check is not getting triggered though the action created by me is correct.

**Comment by marionschleifer** [comment]
@Hard-Coder05 okay no problem. I can take over from here 🙂 thank you for trying!

**Comment by Hard-Coder05** [comment]
Thank You @marionschleifer for guiding me on this PR!

**Comment by marionschleifer** [comment]
This is now working. Whenever there's a file in the `docs/` folder with the extension `png`, `jpg` or `jpeg` the build will only pass when the `docs-images-compress` label is added. Otherwise, it will give the following error:

image

**Review by marionschleifer — APPROVED** [review]

**Comment by Hard-Coder05** [comment]
@marionschleifer Am I eligible for the hacktoberfest swags??

**Comment by mehtavishwa30** [comment]
@Hard-Coder05 Thanks so much for your contribution! We'll be sending you an email with the swag form shortly which you can fill up and get some super cool Hasura swag sent to you. ✨

**Comment by rikinsk** [comment]
We recently managed to add a workflow where we can now directly compress iamges on PRs (see [commit](https://github.com/hasura/graphql-engine/commit/f319b02766f904dc3e17d3862d08a849d54871c3)). Hence closing this now as it would not be required anymore.

Thanks a ton for raising this PR though. We really appreciate the effort you've put in for us!

**Pull request closed without merging**
