### PR TITLE
docs: update clouds screenshots throughout docs

### PR DESCRIPTION
**Pull request by akarsh-jain-790**
Fixes: #8998

### Description
Update all screenshots throughout documentation

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

### CODE REVIEW

**Comment by akarsh-jain-790** [comment]
@robertjdominguez Have implemented your suggested changes, you can re-review now.

**Comment by robertjdominguez** [comment]
Thanks for the revisions and for opening a new PR, @akarsh-jain-790 👍 

Recently, we've added Neon as a database partner for creating serverless Postgres databases from the Console. Previously, this was Heroku; some of your screenshots (e.g., `docs/static/img/cloud-dbs/existing-db-setup.png`) are outdated. Would you be willing to update these?

**Review by robertjdominguez — CHANGES_REQUESTED** [review]
Thanks for the updates @akarsh-jain-790 👍 

Hopefully last bits of feedback, and then we can merge.

`docs/static/img/cloud-dbs/existing-db-setup.png`:

- Can we crop this image to match the original amount of the UI shown?

`docs/static/img/cloud-dbs/hasura-console.png`

- Great update 👍 

`docs/static/img/databases/read-replicas/connect-db-with-replica.png`

- Let's crop this, so it focuses on the Read Replicas section.

`docs/static/img/getting-started/connect-db-cloud.png`

- Somebody actually recently merged a change to this image that is up-to-date. You can either revert or match your cropping to make the same amount of the UI visible in your screenshot.

`docs/static/img/getting-started/connect-db-console.png`

- Good update 👍 

`docs/static/img/getting-started/create-profile-table.png`

- Could we crop out the dark bar on the left-hand border?

`docs/static/img/getting-started/db-setup.png`

- Same feedback as `docs/static/img/getting-started/connect-db-cloud.png`; whichever you chose for that image, the same goes for this one.

`docs/static/img/getting-started/profile-query.png`

- Great update 👍 

`docs/static/img/getting-started/project-manage.png`

- Could we crop the whitespace on the right-hand border?

`docs/static/img/observability/monitoring-tab-overview.png`

- Good update 👍

**Comment by akarsh-jain-790** [comment]
@robertjdominguez Updated the PR, you can re-review.

**Comment by akarsh-jain-790** [comment]
@robertjdominguez Updated the PR, you can re-review.

**Comment by Stefmore02** [comment]
Hey! @akarsh-jain-790 

Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation and you will be getting an email with the swag form shortly.✨

**Comment by akarsh-jain-790** [comment]
> Hey! @akarsh-jain-790
> 
> Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation and you will be getting an email with the swag form shortly.✨

@Stefmore02 I haven't received the mail yet.

**Comment by Stefmore02** [comment]
> > Hey! @akarsh-jain-790
> > Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation and you will be getting an email with the swag form shortly.✨
> 
> @Stefmore02 I haven't received the mail yet.

@akarsh-jain-790 could you please send me an email to estefani@hasura.io and make a reference of this PR?

**Pull request closed without merging**
