### PR TITLE
allow to track all tables/relationships (close #1418)

### LINKED ISSUE #1418: cli: allow to track all tables/relationships
When using Hasura with an existing database, it would be super useful to be able to track all tables and all relationship with the cli (instead of having to go in the console in the browser) (eg for scripts or functional tests)

### PR DESCRIPTION
**Pull request by arvi3411301**
### Description
CLI will be having the below command in order to track and untrack tables, relationships across schemas.

```
# track all tables in public schema
hasura metadata track --all-tables [--schema public]

# track all tables and relationships in public schema
hasura metadata track --all-tables --all-relationships

# track only 2 tables and relationships among them
hasura metadata track --table author --table article --all-relationships

# track all tables in schema1 and schema2
hasura metadata track --all-tables --schema schema1 --schema schema2

# track only one table table1 from schema1
hasura metadata track --table table1 --schema schema1

# track all tables relationships, but export as migration
hasura metadata track --export-as-migration
```

```
# untrack all tables in a schema
hasura metadata untrack --all-tables --schema schema1

# untrack only 1 table
hasura metadata untrack --table table1 --schema schema1
```

### Affected components 

- CLI
- Docs

### Related Issues
#1418 

### Limitations, known bugs & workarounds
~~Table and relationships across schemas cannot be tracked~~

### CODE REVIEW

**Comment by karthikvt26** [comment]
```
./hasura metadata track --table table_1 --table table_2 --all-relationships
```
screenshot 808

The issue is `table_2` has a foreign key to `table_3` and the command is trying to track that too.

This issue is there on console too tracked in #1882

**Comment by arvi3411301** [comment]
@shahidhk What should we do in this case?

**Comment by arvi3411301** [comment]
@karthikvt26 Is the relationships name generated is according to the console?

**Comment by karthikvt26** [comment]
@arvi3411301 Yes

**Comment by shahidhk** [comment]
1. We should only track relations across the tables and schema that are being tracked.
2. Trying to track a table that is already tracked should succeed, but with a message saying the table is already tracked.
3. Tracking a table that doesn't exist should fail.

Also, while tracking all tables relations etc, the logs should clearly output what is tracked.

**Comment by rikinsk** [comment]
> Trying to track a table that is already tracked should succeed, but with a message saying the table is already tracked.
 
Will this also work for the track metadata API. Currently on SQL page if the checkbox is tracked and the table is already tracked the entire operation fails

**Comment by arvi3411301** [comment]
@karthikvt26 I had fixed column conflicts. Can you try again if this build fixes all issues?

**Comment by karthikvt26** [comment]
@arvi3411301 Running with --table and --all-relationship option is not tracking the relationships

```
➜  my-project ./hasura-dev metadata track --table table_1  --all-relationships
ERRO auto-update failed, run 'hasura update-cli' to update manually  error="cannot update from a non-semver version: pull1876-474ab73"
INFO tables/relationships tracked successfully    
➜  my-project ./hasura-dev metadata track --table table_2  --all-relationships
ERRO auto-update failed, run 'hasura update-cli' to update manually  error="cannot update from a non-semver version: pull1876-474ab73"
INFO tables/relationships tracked successfully    
```

screenshot 834
screenshot 833

**Comment by arvi3411301** [comment]
@karthikvt26 In order to track relationships across tables, you need to specify --table table2.

**Comment by karthikvt26** [comment]
Ok the message is slightly confusing then (`table/relationships tracked successfully`)

**Comment by arvi3411301** [comment]
@karthikvt26 We will be adding info/warn messages if something is missing.

Something like,

WARN: relationship referencing to table2 (cols) from table1 (cols) cannot be created since --table table2 is missing from command.

**Comment by karthikvt26** [comment]
@arvi3411301 No no can we add Logs as 
1) INFO tables tracked successfully    
2) INFO relationships tracked successfully  (will not be there if no relationships are tracked)

@shahidhk

**Comment by shahidhk** [comment]
@arvi3411301 Why was this closed?

**Comment by arvi3411301** [comment]
@shahidhk need to rewrite everything. Will open a new PR.

**Pull request closed without merging**
