### PR TITLE
add "Edit on GitHub" link in the docs. (close #1480)

### LINKED ISSUE #1480: add "Edit on GitHub" link in the docs
It would be nice to have a link on each page in the docs that allows you to jump right to the corresponding file in GitHub in order to lower the barrier to entry for docs corrections and PRs.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
### Description

This PR adds a link to GitHub file for the page currently viewed on the docs.

What component does this PR affect? 

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [x] This change requires a change in the documentation. 
- [x] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by praveenweb** [comment]
@Anupam-dagar - Can you fix the conflicts? Also what was the method used to add github links to existing docs?

@rikinsk - Shouldn't this be automated?

**Comment by Anupam-dagar** [comment]
@praveenweb, I did this manually. Looked in sphinx docs but didn't found something relevant.

**Comment by rikinsk** [comment]
@Anupam-dagar This can be templated in the layout itself. I'll get back in sometime with the changes required for this

**Comment by rikinsk** [comment]
Closing in favour of #1519

**Pull request closed without merging**
