### PR TITLE
Fix bulk deleting roles without permissions close #4178

### LINKED ISSUE #4178: "Remove all permissions" button not working
Not sure what's going on, selecting one or many permissions.

Screen Shot 2020-03-24 at 15 49 19

Browser: Safari
Hasura: v1.1.0

### PR DESCRIPTION
**Pull request by sobrinho**
### Description

Roles without any permissions can't be bulk deleted and throws an error as described in #4178.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

#4178 

### Solution and Design

Do not render the checkbox for roles without any permission. That way, the user can't select it.

### Steps to test and verify

Try to mark and bulk delete a role without any permissions configured in a table, watch the inspector before doing it.

### Limitations, known bugs & workarounds

N/A

### Server checklist

N/A

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by sobrinho** [comment]
Alright, I will do it.

**Comment by sobrinho** [comment]
@rikinsk done!

**Comment by beerose** [comment]
In v.1.1.0 we were showing a checkbox for a new role without permissions, which resulted in error described in #4178. But in this PR https://github.com/hasura/graphql-engine/pull/3889 we added `showCheckbox` which conditionally renders checkbox.
What is the example scenario in which I can see a disabled checkbox with `No permissions exist` title?

**Comment by rikinsk** [comment]
@beerose If you have a role used in one table but not used in another table

**Comment by beerose** [comment]
Thank you! Approving.

**Pull request merged**
