### PR TITLE
New ENV variable support for disabling CORS headers (close #3782)

### LINKED ISSUE #3782: add env var for disabling cors headers
Currently, in order to disable cors headers, the `--disable-cors` flag needs to be set.

We should add an environment variable that will allow to do the same.

The docs need to be updated accordingly: https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#command-flags.

### PR DESCRIPTION
**Pull request by sordina**
Note: This is my first PR and as such am very happy to take advice on the process. I'm especially interested in how the corresponding documentation should be updated and what the testing process is.

### Description

As requested in [issue 3782](https://github.com/hasura/graphql-engine/issues/3782) there is currently no support for selecting the `--disable-cors` option via environment variable. Most other options have corresponding environment variables as [documented here](https://docs.hasura.io/1.0/graphql/manual/deployment/graphql-engine-flags/reference.html#command-flags).

The new environment-variable is `HASURA_GRAPHQL_DISABLE_CORS`.

### Affected components

- [x] Server
- [x] Docs

### Related Issues

* #3782 

### Solution and Design

I've followed the pattern used by several other env-variable supported options in the `server/src-lib/Hasura/Server/Init.hs` file. This included adding a new variable-documentation tuple and referencing it in where the non-raw cors-options are constructed.

### Steps to test and verify

Presence should be able to be tested by listing long-form options help for the server. In addition, I would like to be able to dump the options structure but am not currently sure how to do this.

Print options with `cabal new-run graphql-engine serve -- --help`.

#### Catalog upgrade

Does this PR change Hasura Catalog version?

- [x] No

#### Metadata

Does this PR add a new Metadata feature?

- [x] No

#### GraphQL

- [x] No new GraphQL schema is generated

#### Breaking changes

- [x] No Breaking changes

If someone happens to be using the environment variable `HASURA_GRAPHQL_DISABLE_CORS` for another purpose, this will conflict.

### CODE REVIEW

**Comment by marionschleifer** [comment]
@sordina thank you so much for your PR 🙏 is this PR ready for review or are you still working on it? If it's ready, you can remove the `WIP` in the title 🙂

**Comment by sordina** [comment]
Hi @marionschleifer 

Thanks for taking a look! I left the WIP tag as I wasn't sure if it was up to an acceptable standard or not, but I'll remove the WIP title as it seems like that's all part of the review process :)

**Comment by sordina** [comment]
@marionschleifer @ecthiender What is the process for updating the linked documentation by the way?

**Comment by marionschleifer** [comment]
@sordina you find everything about how to set up the dev environment for docs in our [docs contributing guide](https://github.com/hasura/graphql-engine/blob/master/docs/CONTRIBUTING.md). Please let me know if you have questions of if something is not clear 🙂

**Comment by sordina** [comment]
Thanks @marionschleifer I updated the corresponding docs file. Just curious, how are the docs on the site versioned? It appears that there's currently only a v1.0, but that may change?

image

**Comment by marionschleifer** [comment]
@sordina good question 😄 we'll have different versions of the documentation, but only for the major versions, like 1.0. And then again for 2.0. Hope this answers your question 🙂

**Comment by 0x777** [comment]
@ecthiender 
> do you think we need to add tests for this?

Ideally yes, but currently we lack a mechanism to check the options that graphql-engine loaded from command line arguments and env variables. I'll open a different issue to track this.

**Comment by sordina** [comment]
Thanks everyone!

**Pull request merged**
