### PR TITLE
Docs-update screenshots part of issue #8883

### PR DESCRIPTION
**Pull request by Ln11211**
### Description

Updated the outdated screenshots of docs. **This PR is work in progress...**
### Changelog

__Component__ : server / cli / console / build 

__Type__: bugfix / feature / enhancement 

__Product__: community-edition

### Related Issues

The related issue is #8883 
#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by Ln11211** [comment]
Any changes you want @robertjdominguez ?

**Comment by robertjdominguez** [comment]
> Any changes you want @robertjdominguez?

Thanks for this @Ln11211 👍 

This is a good iteration, but there's still some work to make things more consistent:

- [ ] Make sure all your arrows are in the correct style (shape, with tapered tail) and use the hex value: `#FC336D`. Some still utilize `#F00000`.
- [ ] The borders for your callouts utilize different widths; some are far too thin and will be difficult to see in the body of a page.
- [ ] Make sure all the borders on callouts have an equal margin around their focal point and have clean, 90 deg. angles connecting each leg.

Shout with any questions 👍

**Comment by robertjdominguez** [comment]
@Ln11211, I've been keeping an eye on this PR and know you made [this commit](https://github.com/hasura/graphql-engine-mono/commit/908a4cdc74fc6e5ccd56a6a3d1a66b0dc4b5389e) last week. Double-checking if you're ready for a re-review, as several of the images included still have the wrong hex values.

**Comment by robertjdominguez** [comment]
Closing this as stale.

**Pull request closed without merging**
