### PR TITLE
serve apis at a root other than / (close #1141)

### LINKED ISSUE #1141: expose apis and console at a path other than /
This will enable serving the APIs at a non-root path like `/hasura/v1alpha1/graphql`, `/hasura/console`

Related to #1069.

### PR DESCRIPTION
**Pull request by rakeshkky**
### Description

What component does this PR affect? 

- [x] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Related Issue

close #1141 

### Solution and Design

Allow server APIs and console to be served at a path other than `/` 
configurable via `--url-root` command line flag and 
`HASURA_GRAPHQL_URL_ROOT` environment variable

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [x] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by shahidhk** [comment]
@rakeshkky, I set `--url-root hello`. Now, if I go to `/`, I get redirected to `/hello/console`, which is okay, I guess.

But if I go to `/hello` I get 404. `/hello` should redirect to `/hello/console` -- basically it should issue `301 console`

**Comment by shahidhk** [comment]
@praveenweb Looks like the console is not respecting the prefix when generating the API url.

**Comment by danieldunderfelt** [comment]
Awesome to see this on the way, as this issue is blocking our use of Hasura on a server with many projects on it!

**Comment by shahidhk** [comment]
ref https://github.com/hasura/graphql-engine/issues/1141#issuecomment-447758193 for more info

**Comment by 0x777** [comment]
closing this in favor of https://github.com/hasura/graphql-engine/pull/1222

**Comment by cusspvz** [comment]
@0x777 having some option that allows us to set a `prefix` on all the server's endpoints would def bring value to Hasura. 

As explained at [this comment](https://github.com/hasura/graphql-engine/issues/1141#issuecomment-447758193), whenever someone wants to expose hasura on a different path, we need to either get a load-balancer capable of trimming a prefix off the path or place an `nginx` service that does that. 

It seems that this was already done in this effort/PR, but it wasn't merged because the need for this was fixed by other PR.

@0x777 Is there a plan to include an option on the graphql-server similar to this one?

**Pull request closed without merging**
