### PR TITLE
docs: update clouds screenshots throughout docs

### PR DESCRIPTION
**Pull request by akarsh-jain-790**
Fixes: #8998

### Description
Update all screenshots throughout documentation

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

### CODE REVIEW

**Comment by robertjdominguez** [comment]
Hi @akarsh-jain-790 👋 

Thanks for taking the initiative on this PR! We have a [style guide](https://hasura.io/docs/wiki/style/images/) with standards we try to hold across docs; could you take a look and make revisions based on what you find?

Specifically, with these kinds of screenshots, we want to encourage uniformity and anonymity with information. That means removing references to project endpoints, schemas, etc.

Shout with any questions and happy Hacktoberfest 🎃

**Comment by akarsh-jain-790** [comment]
@robertjdominguez Have implemented your suggested changes, please let me know if there is anything else I can improve!

**Comment by robertjdominguez** [comment]
Thanks @akarsh-jain-790 🔥 

A big piece of our style guide is uniformity in the scale of images, as you can see from [this section in our wiki](https://hasura.io/docs/wiki/style/images/#scale). Could you try again with the listed dimensions (specifically, a width of `1200px`)?

**Comment by akarsh-jain-790** [comment]
> Thanks @akarsh-jain-790 🔥
> 
> A big piece of our style guide is uniformity in the scale of images, as you can see from [this section in our wiki](https://hasura.io/docs/wiki/style/images/#scale). Could you try again with the listed dimensions (specifically, a width of `1200px`)?

@robertjdominguez I have took the screenshots according to the guideline. Also not all ss can be of 1200px so what should I do in that case?

**Comment by robertjdominguez** [comment]
> Also not all ss can be of 1200px so what should I do in that case?

Good question! If a page - for example, the API tab - is too wide to conform to our guidelines, then please seek to come as close as possible to `1200px`.

Another example: [this screenshot](https://github.com/hasura/graphql-engine/pull/9090/files#diff-c7a82b712215b1db2ee3f6827e806401b76c355f7a4c02df3c287039bb3740f5) could be significantly smaller to meet our guidelines.

**Pull request closed without merging**
