### PR TITLE
Docs-update screenshots close #8883

### LINKED ISSUE #8883: docs: update screenshots
### Problem description

Screenshots have mostly been updated for Cloud related docs (identified by the ☁️ icon on docs) and for the Enterprise docs (identified by the 🏢 icon on docs). 

A lot of the screenshots of the feature docs are outdated.

### Describe the solution you'd like

Update the updated screenshots.

### Instructions

Please read carefully through the [Wiki on writing documentation](https://hasura.io/docs/wiki/), especially the [images section](https://hasura.io/docs/wiki/style/images/).

### PR DESCRIPTION
**Pull request by Ln11211**
### Description

Updated the outdated screenshots of docs. **This PR is work in progress...**
### Changelog

__Component__ : server / cli / console / build 

__Type__: bugfix / feature / enhancement 

__Product__: community-edition

### Related Issues

The related issue is #8883 
#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by Ln11211** [comment]
This PR is a work in progress. Updated the screenshots of the following docs until now-
- docker-simple.mdx (4 ss)

**Comment by robertjdominguez** [comment]
Hey @Ln11211 - just checking in since you've marked these as WIP...any progress or desire for review yet? Thanks!

**Comment by Ln11211** [comment]
hello there, I'll be uploading more docs soon, I'll ping you as soon as I commit them :-)

**Comment by Ln11211** [comment]
- [x] getting-started/docker-simple
- [x] databases/connect-db/index
- [x] databases/connect-db/read-replicas
- [x] databases/postgres/citus-hyperscale-postgres/getting-started/cloud
- [x] databases/postgres/citus-hyperscale-postgres/getting-started/docker
- [x] databases/ms-sql-server/getting-started/cloud
- [x] databases/ms-sql-server/getting-started/docker
- [x] databases/bigquery/getting-started/cloud
- [x] databases/bigquery/getting-started/docker
- [ ] schema/postgres/tables
- [ ] schema/postgres/table-relationships/create
- [ ] schema/postgres/remote-relationships/remote-source-relationships
- [ ] schema/postgres/remote-relationships/remote-schema-relationships
- [ ] schema/postgres/remote-relationships/action-relationships
- [ ] schema/postgres/views
- [ ] schema/postgres/custom-functions
- [ ] schema/postgres/default-values/postgres-defaults
- [ ] schema/postgres/default-values/sql-functions
- [ ] schema/postgres/default-values/column-presets
- [ ] schema/postgres/default-values/created-updated-timestamps
- [ ] schema/postgres/enums
- [ ] schema/postgres/computed-fields
- [ ] schema/postgres/custom-field-names
- [ ] schema/postgres/naming-convention
- [ ] schema/postgres/data-validations
- [ ] schema/postgres/using-existing-database  (this page is missing photos although it should have photos for the console)
- [ ] schema/postgres/relay-schema
- [ ] schema/ms-sql-server/tables
- [ ] schema/ms-sql-server/table-relationships/create
- [ ] schema/ms-sql-server/remote-relationships/remote-source-relationships
- [ ] schema/ms-sql-server/views
- [ ] schema/ms-sql-server/default-values/mssql-defaults
- [ ] schema/ms-sql-server/default-values/mssql-column-presets
- [ ] schema/ms-sql-server/using-existing-database (this page is missing photos although it should have photos for the console)
- [ ] schema/bigquery/tables
- [ ] schema/bigquery/custom-field-names (needs attention!!, @Stefmore02 can check this out? )
- [ ] schema/bigquery/table-relationships/create
- [ ] schema/bigquery/remote-relationships/remote-source-relationships
- [ ] schema/bigquery/remote-relationships/remote-schema-relationships
- [ ] schema/bigquery/computed-fields
- [ ] schema/bigquery/data-validations

**Comment by Ln11211** [comment]
hello @robertjdominguez,
I hope you are doing good, I have updated the screenshots for the UI in the schema/postgres docs, could you please check them all while I start with the schema/ms-sql-server docs (see the check list in the top ^^) . 


**NOTE** : **I am using the previous names for the screenshots so that way I would only need to change the image files and not the `src tag` in the documentation. This saves me some time when I update the images. Please do let me know if I have to change any images.**

**Comment by Ln11211** [comment]
image


Hey @robertjdominguez , this branch is 67 commits behind the master branch and I can't merge the commits automatically, can I go ahead and create a pr in my repo to merge those commits ?

**Comment by robertjdominguez** [comment]
> Hey @robertjdominguez , this branch is 67 commits behind the master branch and I can't merge the commits automatically, can I go ahead and create a pr in my repo to merge those commits ?

Hi @Ln11211 👋 

You won't be able to merge yourself; our CI processes will take care of that if the PR is approved. I've had a chance to look over this; you've done a lot of work and we thank you for that! 🥳 

I do have some feedback that may make it difficult, depending on how you've completed these screenshots, to reconcile:

Our wiki, which is linked in the original issue, makes note that we use a very specific hex value for our callouts (arrows, boxes, etc.). Your screenshots utilize `#fa4a42` while [we require](https://hasura.io/docs/wiki/style/images/#callouts-arrows-and-other-screenshot-markup) `#fc336d`. It's subtle, but there's a difference.

Would you be willing to update your work?

**Comment by Ln11211** [comment]
> You won't be able to merge yourself; our CI processes will take care of that if the PR is approved. I've had a chance to look over this; you've done a lot of work and we thank you for that! 🥳

no no not merge this PR, I want to merge the commits to this branch, I am behind the original tree I mean I still have the docs-old with me
 
> Our wiki, which is linked in the original issue, makes note that we use a very specific hex value for our callouts (arrows, boxes, etc.). Your screenshots utilize `#fa4a42` while [we require](https://hasura.io/docs/wiki/style/images/#callouts-arrows-and-other-screenshot-markup) `#fc336d`. It's subtle, but there's a difference.
> 
> Would you be willing to update your work?

Yes yes, I'll change them.

**Comment by robertjdominguez** [comment]
You should be able to run `git merge master` from your branch and resolve any conflicts.

**Comment by Ln11211** [comment]
Hey @robertjdominguez , I changed the hex values of the arrows and boxes but I have many conflicts, I resolved the conflicts but I have about 164 commits(that I have to push to my branch), I thin I will break the `master` branch so, Can I please close this PR and raise a new one?

**Comment by robertjdominguez** [comment]
If it's easiest for you to open a new PR, @Ln11211 then please do so 👍

**Comment by Ln11211** [comment]
> If it's easiest for you to open a new PR, @Ln11211 then please do so 👍

I apologize for messing my working branch :/

**Pull request closed without merging**
