### PR TITLE
Update query.mdx for boolean expresssions - close #9056

### LINKED ISSUE #9056: Docs for Boolean expressions are incomplete
The API docs specify that a Boolean expression (e.g. for `where` clauses) is one of five options.
https://github.com/hasura/graphql-engine/blob/52873dba95df9aac8dfee174597c7967291e4828/docs/docs/api-reference/graphql-api/query.mdx#L366-L384
In particular, `ColumnExp` simply represents a comparison operator.
https://github.com/hasura/graphql-engine/blob/52873dba95df9aac8dfee174597c7967291e4828/docs/docs/api-reference/graphql-api/query.mdx#L578-L620

At first sight, this is matched by the internal Haskell representation: a `GBoolExp` is one of five options.
https://github.com/hasura/graphql-engine/blob/52873dba95df9aac8dfee174597c7967291e4828/server/src-lib/Hasura/RQL/IR/BoolExp.hs#L81-L90
However, in most cases, the `a` type parameter used by `BoolFld` is filled in by `AnnBoolExpFld`:
https://github.com/hasura/graphql-engine/blob/52873dba95df9aac8dfee174597c7967291e4828/server/src-lib/Hasura/RQL/IR/BoolExp.hs#L504-L517
This allows for not just a binary operator on a column (`AVColumn`), but also for deeper Boolean expressions in the case of relationships and computed fields.

Concretely, this means that something like
```graphql
query {
  articles(where: {author: {hometown: {_eq:"Amsterdam"}}}) {
    title
  }
}
```
is not considered a valid query by the documentation.

Was this part of the documentation possibly written before support for DB table relationships was added? In any case, it didn't get improved after computed fields were added.

### PR DESCRIPTION
**Pull request by jerempy**
Update to show that columnexp and booleans with can use relationships. Also removed the anchors on headers so that the links will work
close #9056

### Description

The docs concerning the boolean expressions were dated and so didn't express that you could use relationships as part of your queries.
### Changelog

__Component__ : server 

__Type__: bugfix 

__Product__: community-edition

#### Short Changelog

Clarify docs for relationships as part of boolean expressions in queries
#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by abooij** [comment]
Thanks for the PR, @jerempy.

It seems that there are some syntax errors in the code, as the docs build is failing. Perhaps @seanparkross can help you out with that? I'm not too familiar with the syntax of the docs.

As for the changes from a semantic PoV, I'm not so sure. This PR seems to be changing `WhereExp`, rather than `BoolExp`. This brings the docs only marginally closer to what the server actually supports. For instance, what about `where: {_not: {articles: {rating: {_gte: 4}}}}`? This is supported by the server, but not by the docs after (or before) this PR.

**Comment by jerempy** [comment]
@abooij Thanks for the reply and insight! Makes sense. I took another shot at it. lemme know what you think.

**Comment by abooij** [comment]
This new attempt adds a few helpful examples. That's good. However, it doesn't address #9056, because it doesn't change the grammar spelled out in the documentation - that is to say, it doesn't change `BoolExp`, `ColumnExp`, etc. There's something material missing in the actual grammar (namely the possibility to use relationships as part of boolean expressions), not just in the explanation.

@seanparkross could you please help trace down why the build of the docs isn't succeeding?

**Comment by robertjdominguez** [comment]
@abooij, saw your comment via email. I pulled the branch and it ran fine locally. I went to the CI steps and scrolled down to find `Cloudflare` where it says deployed successfully. I don't know why the comment in the `mono` PR didn't update, but you can scroll down there to see the preview build URL.

**Comment by jerempy** [comment]
@abooij thanks for the insight and patience. I took another shot - 🤞 i got it

**Comment by seanparkross** [comment]
@jerempy Thanks for the Hacktoberfest submission from the Docs team! We're going to have some swag coming your way soon. 

In terms of moving forward on this PR we're going to loop back on it nearer the end of the month when our dev teams have more availability. 

Thanks

**Comment by Stefmore02** [comment]
Hey! @jerempy 

We'd love to send you some Hasura swag as a token of appreciation. Could you please send me an email to estefani@hasura.io with a reference of this PR so I can send you the swag form? ✨

**Pull request closed without merging**
