### PR TITLE
Documentation to deploy on AWS Fargate and RDS DB

### LINKED ISSUE #583: docs: add deploying guide on aws fargate
[AWS Fargate](https://aws.amazon.com/fargate/) is a service to run containers without managing servers or clusters. Since Hasura is just a docker image, it can be deployed to Fargate easily.

The guide can be added at https://hasura.io/docs/1.0/graphql/core/deployment/deployment-guides/index.html.

It'll be great if the Postgres setup can be on Amazon RDS. Should have updating and setting access key instructions.

### PR DESCRIPTION
**Pull request by moulikcipherX**
### Description

What component does this PR affect? 

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [x] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System

### Related Issue
close/fix #583 

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Docs update
- [x] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [x] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by shahidhk** [comment]
Thanks for the PR @moulikcipherX :pray: 

@rikinsk will review the content.

Can you exaplain why ` Setting up our Repository on AWS ECS using AWS CLI ` step is required? `hasura/graphql-engine` is a public repo. Why do we need to create a new ECR repo and push graphql engine there?

**Comment by shahidhk** [comment]
Okay, but shouldn't update the docs to the correct method? :laughing:

**Comment by moulikcipherX** [comment]
I know get that about repository as ECS take repository URI when cluster is created so we have to upload in ECS repository only..

**Comment by moulikcipherX** [comment]
@shahidhk Sir any update on merging??

**Comment by shahidhk** [comment]
@moulikcipherX We need to remove the ECR registry creation step :smile:

**Comment by moulikcipherX** [comment]
@shahidhk sir the task definitions take image URI of ECS repository only so we can't skip that step.

**Comment by shahidhk** [comment]
@moulikcipherX I will verify the instructions and get back to you.

**Comment by moulikcipherX** [comment]
Any Update?

**Comment by elgordino** [comment]
@moulikcipherX it is not necessary to use ECR with Fargate. I use this in my configuration and it works fine

            "image": "hasura/graphql-engine:v1.0.0-alpha29",

**Comment by coco98** [comment]
This is the file that @elgordino mentioned using:
https://gist.github.com/coco98/318f24a7074a95a8b22e139f88292d5a

**Comment by shahidhk** [comment]
Closing this PR since better ways to deploy to Fargate have been documented at https://dev.to/lineup-ninja/deploying-hasura-on-aws-with-fargate-rds-and-terraform-4gk7, https://github.com/hasura/hasura-aws-stack, and https://github.com/Rayraegah/terraform-aws-hasura

All of them have been linked to from https://github.com/hasura/graphql-engine/wiki/Community

**Pull request closed without merging**
