### PR TITLE
enable redux-dev-tools if present in dev mode (closes #606)

### LINKED ISSUE #606: Cannot use redux-dev-tools extension to follow state updates
Hello !

https://github.com/zalmoxisus/redux-devtools-extension/ is a really popular and useful tool to monitor and follow your state updates.
It could be great if we could use it in development mode.

### PR DESCRIPTION
**Pull request by kraynel**
### Description

Enables redux-dev-tools in development mode.

What component does this PR affect? 

- [ ] Server
- [X] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Related Issue

https://github.com/hasura/graphql-engine/issues/606

### Solution and Design

image

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [X] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [x] This change requires a change in the documentation. 
- [x] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by shahidhk** [comment]
@praveenweb @karthikvt26 Please review!

**Comment by karthikvt26** [comment]
@kraynel Thank your the wonderful PR. It looks good :trophy:. Can you also update the console README with this as an optional thing for development?

**Comment by karthikvt26** [comment]
@kraynel any update on this?

**Comment by kraynel** [comment]
> @kraynel any update on this?

Of course, I'll try and commit that today.

**Pull request merged**
