### PR TITLE
docs : Updated screenshots in the docs fixes #8998

### LINKED ISSUE #8998: docs: update clouds screenshots throughout docs
### Is your proposal related to a problem?
Currently, on our documentation, we have a series of outdated Hasura Cloud screenshots. While these are mostly present in our cloud database guides there maybe others throughout documentation. 

### Describe the solution you'd like
To solve this a PR would need to be raised that updates all existing screenshots of Cloud that are not consistent with `v2.12.0-cloud.1`.

In order to update these screenshots, please consider these guidelines:
* Consult our wiki for guidance on [file-naming conventions](https://hasura.io/docs/wiki/style/images/#file-name).
* Consult our wiki for guidance on [callouts and arrows](https://hasura.io/docs/wiki/style/images/#callouts-arrows-and-other-screenshot-markup).
* Consult our wiki for guidance on where to [add files](https://hasura.io/docs/wiki/page-structure/#images).

### PR DESCRIPTION
**Pull request by BajajAyush**
Fixes #8998 
### Description
Updated screenshots related to new cloud version in many places of the docs, includes screenshots that the previous pr by @akarsh-jain-790 has missed.

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

### CODE REVIEW

**Review by seanparkross — APPROVED** [review]
Looks great! Thanks for the submission!

**Review by robertjdominguez — CHANGES_REQUESTED** [review]
@BajajAyush, this is a great PR! We have one tiny nitpick: The arrow's tail in your `/getting-started/project-manage.png` image needs to be tapered as we have in other examples (such as in the out-of-date version).

Can you please update, and we'll approve? Thanks for this great contribution!

**Comment by akarsh-jain-790** [comment]
@BajajAyush  I have already updated this Screenshots in #9141 

`docs/static/img/observability/monitoring-tab-overview.png` 
`docs/static/img/getting-started/connect-db-cloud.png`
`docs/static/img/getting-started/create-profile-table.png`
`docs/static/img/getting-started/profile-query.png`
`docs/static/img/getting-started/project-manage.png`

**Comment by BajajAyush** [comment]
> @BajajAyush, this is a great PR! We have one tiny nitpick: The arrow's tail in your `/getting-started/project-manage.png` image needs to be tapered as we have in other examples (such as in the out-of-date version).
> 
> Can you please update, and we'll approve? Thanks for this great contribution!

Sure, I will do that, please give me time till the end of day

**Comment by BajajAyush** [comment]
> @BajajAyush  I have already updated these Screenshots in #9141 
> 
> `docs/static/img/observability/monitoring-tab-overview.png` 
> `docs/static/img/getting-started/connect-db-cloud.png`
> `docs/static/img/getting-started/create-profile-table.png`
> `docs/static/img/getting-started/profile-query.png`
> `docs/static/img/getting-started/project-manage.png`

I never said that you didn't do it, I said that you have missed a few of them which I have included in my PR. Hope it clarifies

**Comment by seanparkross** [comment]
Hi @BajajAyush and @akarsh-jain-790 

Give us some time to edit these PR's... we're making it so both can be merged. Thanks

**Comment by BajajAyush** [comment]
> @BajajAyush, this is a great PR! We have one tiny nitpick: The arrow's tail in your `/getting-started/project-manage.png` image needs to be tapered as we have in other examples (such as in the out-of-date version).
> 
> Can you please update, and we'll approve? Thanks for this great contribution!

Hey, since it has been merged, I don't have to do this now?

**Comment by robertjdominguez** [comment]
> Hey, since it has been merged, I don't have to do this now?

Correct @BajajAyush 👍

**Comment by Stefmore02** [comment]
Hey! @BajajAyush 

Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation and you will be getting an email with the swag form shortly.✨

**Pull request closed without merging**
