### PR TITLE
add onegraph explorer to console

### LINKED ISSUE #1616: Add onegraph graphiql explorer to console
Let's integrate the onegraph graphiql explorer into the console asap!
https://github.com/OneGraph/graphiql-explorer

@wawhal @rikinsk Any thoughts on complexity?

### PR DESCRIPTION
**Pull request by wawhal**
### Description

Add [OneGraph Explorer](https://github.com/OneGraph/graphiql-explorer) to console. You can now see something like [this](https://www.onegraph.com/graphiql) in the console.

### Affected components 

- Console

### Related Issues

#1616 

### Solution and Design

- Rendering OneGraphExplorer along with existing GraphiQL.
- Added a `Toggle Explorer` button to `hasura-console-graphiql` (our own fork of GraphiQL)

### Steps to test and verify

Click on the toggle explorer button.

### CODE REVIEW

**Comment by coco98** [comment]
@wawhal @shahidhk @arvi3411301 Why don't we have a heroku build for this yet?

**Comment by arvi3411301** [comment]
@coco98 console build is failed for the latest commit.

**Comment by shahidhk** [comment]
There is a scroll bar on the Explorer header. 
https://screenshots.firefox.com/XIuiyjwZ8DG6z5jE/hge-ci-pull-1680.herokuapp.com

Also, shouldn't we say OneGraphiQL somewhere?

**Comment by shahidhk** [comment]
Explorer is super awesome! One tiny feedback that I have is - missing the ability to resize the width of the Explorer column. It is too big for small schemas and takes up a lot of space.

@wawhal

**Comment by coco98** [comment]
and for large schemas with long names its probably a nightmare. lets test
witg a few differemt kinds of lengths and oerhaos allow resize?

**Pull request merged**
