### PR TITLE
add: Apply seeds in cli-migrations fix #7914

### LINKED ISSUE #7914: Apply seeds in cli-migrations v3
### Is your proposal related to a problem?

The CLI Migrations docker image currently only applies the migrations and the metadata, the proposal is for it to also apply the `seeds` when the directory is present

### Describe the solution you'd like

- If the `hasura-seeds` directory is mounted to the container, apply the seeds

### If the feature is approved, would you be willing to submit a PR?

Yes, already on it

### PR DESCRIPTION
**Pull request by preetjdp**
### Description

This PR adds the ability for the seeds to be auto-applied as part of the `cli-migrations` docker image ([Reference](https://hasura.io/docs/latest/graphql/core/migrations/advanced/auto-apply-migrations.html)

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)
- [x] Cli Migrations

### Solution and Design

The PR follows the existing pattern of the [Docker Entrypoint file](https://github.com/hasura/graphql-engine/blob/master/scripts/cli-migrations/v3/docker-entrypoint.sh) and adds a check to apply the seeds if the directory is loaded/present in the file

### Steps to test and verify

The [test file](https://github.com/hasura/graphql-engine/blob/master/scripts/cli-migrations/v3/test/test.sh) has also been updated to show that the seeds have been updated

- Build the `cli-migrations` image locally

```
docker build --build-arg SERVER_IMAGE_TAG=v2.0.8 --no-cache -t cli-migrations-seeds-local-test:3.cli-migrations-v3-arm64 .
```

- Replace the image with the locally built image

image

- Run the test script

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by luisgurmendez** [comment]
This is great! I was wondering if there is an ETA on this

**Comment by luisgurmendez** [comment]
@preetjdp is there something I can do speed-up this pr?

**Comment by preetjdp** [comment]
> @preetjdp is there something I can do speed-up this pr?

This PR was raised back in December of 21', and a whole bunch of changes have been made to the scripts since then, let me close this PR and raise another one

**Comment by preetjdp** [comment]
@luisgurmendez Reopened the PR with the latest changes, closing this PR

~
Could you bump 👍 the PR

https://github.com/hasura/graphql-engine/pull/8721

**Comment by luisgurmendez** [comment]
Thanks :)

**Pull request closed without merging**
