### PR TITLE
[WIP] Add: View in voyager function #314

### LINKED ISSUE #314: View in voyager [proposal]
What about something like a button “View in voyager” that opens up the Schema in an embedded voyager screen!

[link to graphql-voyager!](https://github.com/APIs-guru/graphql-voyager)

### PR DESCRIPTION
**Pull request by vshelke**
### Description
Added a new `VoyagerView` component to view the schema using `graphql-voyager`

What component does this PR affect? 

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Console
- [ ] Server
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Related Issue

proposal for #314 

### Solution and Design
A new `React.Component` is added which renders within the `App` context and opens in a new tab.

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by dsandip** [comment]
Hey @vshelke, this looks promising! The right place for the `Voyager` button is in the /console/data/schema/* pages (in the left nav bar; with a separator grey line after `SQL`):

voyager button placement

Also, good to have but definitely **not** necessary for the first version would be to have the visualization zoom into the table's position in the schema if you are on a `/console/data/schema/<schema-name>/<table-name>/browse` page. E.g. Navigating to https://hge-ci-pull-799.herokuapp.com/console/data/schema/public/tables/Person/browse and then opening Voyager should open the following (with the aforementioned zoom):

screen shot 2018-10-17 at 4 34 42 pm

**Comment by vshelke** [comment]
Hi @dsandip can you help me in understanding this 1 failing test because it seems to have come from components which i have't worked on yet.

**Comment by vshelke** [comment]
The recent commit includes the required updates with the visualisation of zoom into tables position in the schema and also fixed the test. 
Sorry for the late update on this issue. You can review the code to move further with this issue.

**Comment by arvi3411301** [comment]
@vshelke review app is available now for the latest commit.

**Comment by ecthiender** [comment]
@vshelke in the heroku app that is hosted, the voyager screen is stuck at loading. Does it work for you?

**Comment by vshelke** [comment]
Yes, locally after the build step it works in development.

**Comment by dsandip** [comment]
@vshelke The voyager screen has never loaded for me either. Can you troubleshoot this, please? Maybe @praveenweb or @karthikvt26 can help.

**Comment by vshelke** [comment]
Sure @dsandip i will look into the issue. For me after running `npm run build`, i run `npm run dev` the screen comes, as the `voyager.worker.js` file is to be served asynchronously and so the path `/rstatic/dist/` has the file which gets copied after the build process. 

```javascript
<Voyager
     introspection={this.introspectionProvider}
     displayOptions={{ rootType: rootType }}
     workerURI={hasuraconfig.webpackPrefix + 'voyager.worker.js'}
/>
// snippet found in console/src/components/VoyagerView/VoyagerView.js
```
The `Voyager` component needs the file for `workerURI` property and it is not getting loaded as the required js file in not served in production. @praveenweb @karthikvt26

**Comment by vshelke** [comment]
Thank you @praveenweb for the fix!

**Comment by dsandip** [comment]
@vshelke @praveenweb Woohoo! it works! 🚀 

Praveen, @karthikvt26 Review and approve?

**Comment by shahidhk** [comment]
@karthikvt26 @praveenweb Can we review and merge this?

**Comment by praveenweb** [comment]
We still have one more issue. When a type is clicked on the sidebar, the target on the right goes out of focus. The transform: matrix css property value generated is wrong.

Here are two open issues related to the same.

https://github.com/APIs-guru/graphql-voyager/issues/76 and https://github.com/APIs-guru/graphql-voyager/issues/80

**Comment by dsandip** [comment]
@praveenweb What plans of this PR?

**Comment by mnlbox** [comment]
@vshelke Wooooooooooooo It's awesome. Any plan to merge this soon?

**Comment by mnlbox** [comment]
@praveenweb It shows: `Something went wrong`.

**Comment by mnlbox** [comment]
Guys is it ready for merge?

**Comment by FluorescentHallucinogen** [comment]
Any progress?

**Pull request closed without merging**
