### PR TITLE
modify comments for tables/columns and views

### PR DESCRIPTION
**Pull request by praveenweb**

### CODE REVIEW

**Comment by karthikvt26** [comment]
@arvi3411301 review app for this pr?

**Comment by arvi3411301** [comment]
@karthikvt26 status check for server changed from test_and_build_server to build_server.

@shahidhk can we change it back to test_and_build_server?

**Comment by karthikvt26** [comment]
@praveenweb I tested the following usecases

1. Create table

While creating table I encountered a tiny css issue

screenshot 391

2. Saving comment by leaving the input field empty shows [object object] as output

screenshot 392

3. After I clicked on edit, I removed the `[object object]` from the input results in a tiny CSS issue.

screenshot 393

4. Unable to clear added comment under columns

screenshot 394

screenshot 395

5. Can we escape the comment text? If I start with `'` it doesn't let me ( It might not be super important )

screenshot 396

**Pull request merged**
