### PR TITLE
docs: update bash_completion directory typo

### PR DESCRIPTION
**Pull request by slimlime**
Quick typo update.

Correct directory is:
`/etc/bash_completion.d`

For `sudo hasura completion bash --file=/etc/bash_completion.d/hasura`. Current typo in the docs refers to non-existent directory `bash.completion.d`

Reflects install tested on Ubuntu 20.04 LTS

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.
* Updated bash completion path to `/etc/bash_completion.d`

### Affected components

- [x] Docs
- [x] Community Content

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Breaking changes

- [x] No Breaking changes

### CODE REVIEW

**Comment by marionschleifer** [comment]
@slimlime thank you for your contribution? 🙂 could you please sign the CLA?

**Comment by slimlime** [comment]
> Hey thanks for the contribution, a small concern though. The CLI docs are generated based on the help text, so I think we should probably make this change here:
> 
> https://github.com/hasura/graphql-engine/blob/788095acba3cdfda73b03dca62ac1b0331f01456/cli/commands/completion.go#L15

Thank you for pointing out the command line lines and additional context.

Will add those edits in graphql-engine/cli/commands/completion.go and a changelog.md with a concise oneliner outlining the help text update as required

Also noted a few other occurrences in the `deploy-preview` for updating with the additional context of that line and previous help text updates.

Will add those other occurrences as well (Windows (Git Bash))

https://github.com/hasura/graphql-engine/issues/5439

**Comment by marionschleifer** [comment]
@slimlime No need to add to the changelog. I added the `no-changelog-required` label, so the failing test will disappear.

**Comment by marionschleifer** [comment]
@slimlime thank you so much for your contribution 🙏 as a thank you, we'd love to send you some swag. If you're interested, please send an email to marion@hasura.io, and we'll take it from there 🙂

**Pull request merged**
