### PR TITLE
add multirole example to auth docs

### PR DESCRIPTION
**Pull request by dsandip**
### Description
Adds a multirole example loosely based on https://www.youtube.com/watch?v=kHCLQEKjdnI

### Affected components 
- Docs

### Solution and Design
The documented example covers a blog app use-case where users can take one or more of `author`, `reviewer` and `editor` roles.

### CODE REVIEW

**Comment by coco98** [comment]
@shahidhk @arvi3411301 Can we get hasurabot to add a comment with a link to the docs? More convenient and noticeable than checking build logs to get the URL...

**Comment by coco98** [comment]
@dsandip Can you link to the docs page where you've made the changes?

**Comment by dsandip** [comment]
@coco98 https://deploy-preview-1796--hasura-docs.netlify.com/graphql/manual/auth/common-roles-auth-examples.html#multiple-roles-per-user

**Comment by shahidhk** [comment]
@coco98 Configured netlify to comment with the URL.

**Comment by coco98** [comment]
@dsandip The modelling for this example is not neat. 
user_info table can just be user. 
Why does the editor table not have a fk to the arcticle table?

**Comment by coco98** [comment]
Suggestions:

`/auth/common-roles-auth-examples.html` page:
- Anonymous users
- Logged in users
- Using relationships in permissions
- Using arrays in permissions

`/auth/model-roles-in-db.html` page:
- How to model multiple roles in the database
- Current content on multiple roles
- How to structure the UI and make API calls

**Comment by dsandip** [comment]
@coco98 I am incorporating suggestions from your last comment in phases, and with a slight difference:

* Called out use-cases explicity in a dedicated section in the `/auth/basics.html` page itself because this is where we are *currently* highlighting the diff configuration options for permissions: https://deploy-preview-1796--hasura-docs.netlify.com/graphql/manual/auth/basics.html#access-control-use-cases. Pending in this page/section: 
  a) reference `column presets`
  b) arrays in permissions along with #1452 
  c) Move use-cases to a separate page altogether
  d) Add a ton of more information to auth basics

* The current content on multiple roles should stay where it is IMO. I've modified it to have different schemas for each role for the same table (*plus the other feedback*): https://deploy-preview-1796--hasura-docs.netlify.com/graphql/manual/auth/common-roles-auth-examples.html#multiple-roles-per-user

* The `/auth/model-roles-in-auth-and-db.html` page will be added in a separate PR minus the multiple role content (can reference the above example + future guides in this page though)

**Pull request merged**
