### PR TITLE
cli: change 'hasura seeds' to 'hasura seed' with 'seeds' as alias

### PR DESCRIPTION
**Pull request by 27medkamal**
### Description

The correct working cli command is `hasura seeds`. The docs were fixed to use that command instead

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] CLI
- [x] Docs

### CODE REVIEW

**Comment by kolharsam** [comment]
Hey, @27medkamal! Thanks for the PR! 
The original command was envisioned to be `seed` as you can see it in the seed RFC [here](https://github.com/hasura/graphql-engine/blob/master/rfcs/seed-data.md). We now want to extend support to `seeds` as well. 

Here's what you can do to help us out: 
1. change this line https://github.com/hasura/graphql-engine/blob/master/cli/commands/seed.go#L15 to `seed` so that it is the main command and also that all the examples and docs can remain unchanged.
2. append `seeds` to https://github.com/hasura/graphql-engine/blob/master/cli/commands/seed.go#L16 the list of aliases so that `seeds` is also supported. 

Thanks again! 👍

**Comment by 27medkamal** [comment]
Hi @kolharsam 
No problem. I've updated the command and also updated the docs to reflect the new cammand

**Review by kolharsam — COMMENTED** [review]
Hey @27medkamal! Thanks for making the required changes. 
CLI changes LGTM. 

cc @scriptonist

**Review by kolharsam — APPROVED** [review]
CLI

**Review by scriptonist — APPROVED** [review]

**Review by marionschleifer — APPROVED** [review]

**Comment by marionschleifer** [comment]
@27medkamal could you please sign the CLA? Then we can merge this 🙂

**Comment by 27medkamal** [comment]
@marionschleifer Done 👍

**Review by rikinsk — APPROVED** [review]

**Pull request merged**
