### PR TITLE
add few x-forwarded- headers (close #2572)

### LINKED ISSUE #2572: Remote schema forward original user-agent
Hi everyone, 

I have to save all request ip address and user-agent.
Because all request is behind aws load balancer, so i can see original ip address in "x-forwarded-for" in headers. But user-agent is always "hasura-graphql-engine/v1.0.0-alpha44"

How can I forward original user-agent. Thank you very much.

### PR DESCRIPTION
**Pull request by tirumaraiselvan**
### Description

Adds `X-Forwarded-Host` and `X-Forwarded-User-Agent` headers to the remote schema requests.

### Affected components

- [x] Server

### Related Issues
#2572 

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No

#### Metadata

Does this PR add a new Metadata feature?
- [x] No

#### GraphQL
- [x] No new GraphQL schema is generated

#### Breaking changes

- [x] No Breaking changes

### Limitations, known bugs & workarounds

This PR does not forward other headers like `X-Forwarded-For` which is more complicated.

### CODE REVIEW

**Comment by lexi-lambda** [comment]
@tirumaraiselvan The tests you just pushed seem to be failing.

**Comment by tirumaraiselvan** [comment]
Bit of a conundrum. The server in CI seems to be running in localhost:8081.

**Comment by tirumaraiselvan** [comment]
@lexi-lambda I am thinking of dropping the test for `X-Forwarded-Host` as it is dynamic ( but I will keep `X-Forwarded-User-Agent`) ?

**Comment by lexi-lambda** [comment]
Ah, yeah, the tests in CI spin up two instances of `graphql-engine` in parallel. There must be a way to access the current host and port we’re running the tests against from inside the test suite code, so we should use that for the expected value of `X-Forwarded-Host`.

**Comment by tirumaraiselvan** [comment]
We can get the host:port in pytest but the expected value will then somehow will have to be fed to the graphql-server.py (which so far was independent server). Worth the fight?

**Comment by lexi-lambda** [comment]
Ah, I see, right of course. I think it’s probably worth doing—`graphql-server.py` will need to check to see if the host is either of the expected GraphQL servers, so it should probably be fed a list of URLs the same way the core test suite is.

**Comment by tirumaraiselvan** [comment]
Wow awkwardly stumbled on fixing this till I realized that there was only one pytest session but parallelized internally.

**Pull request merged**
