### PR TITLE
[WIP] Add admin role flag (close #2346)

### LINKED ISSUE #2346: Feature: Customize name of "admin" role
Related losely to https://github.com/hasura/graphql-engine/issues/310

It would be a nice-to-have to be able to change the default "admin" role name. I don't think "admin" really describes the role very well in real world use cases. I build an application for a client and give it to them. They are the administrators of the site, they can add users, delete posts etc. I like to call them "admin".

What Hasura is calling "admin" now is more of a "super-user" or "root" who can and must be able to do everything. That's not what I want my site admins to do.

Now I'm struck trying to think of another good name for my admin role...

### PR DESCRIPTION
**Pull request by m13m**
### Description
* Its add the `--admin` flag to serve command

### Affected components 

- Server

### CODE REVIEW

**Comment by m13m** [comment]
I added the flag but can't figure the rest of the steps 

ping @shahidhk

**Comment by shahidhk** [comment]
@m13m Sorry about the delay. What you have to do next is to pass this variable down to the function where permissions are enforced. You can add this to `UserInfo` type in the HandlerCtx (https://github.com/hasura/graphql-engine/blob/master/server/src-lib/Hasura/Server/App.hs#L124) and later retrieve it.

Let us know if you have questions about this.

**Comment by m13m** [comment]
Thanks for the tip @shahidhk I will get this done hopefully by the end the week

**Comment by marionschleifer** [comment]
Hi @m13m, just wanted to check in to see how this is going 🙂

**Comment by marionschleifer** [comment]
I'm closing this PR because of inactivity. @m13m feel free to re-open should you wish to continue working on this 🙂

**Pull request closed without merging**
