### PR TITLE
docs: guide on custom jwt auth integration (close #4441)

### LINKED ISSUE #4441: docs: guide on custom jwt integration
People in the community frequently ask how to integrate Hasura with a custom JWT auth server.

We should write an integration guide on this.

### PR DESCRIPTION
**Pull request by marionschleifer**
### Description

An integration guide for custom JWT auth server.

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [x] Docs

### CODE REVIEW

**Comment by tirumaraiselvan** [comment]
While we are at this, can we have a separate section for `Integration with auth providers` similar to `Integration with monitoring tools`. 

Will need to keep in mind the urls etc are not breaking.

**Comment by GavinRay97** [comment]
@tirumaraiselvan 

When you say keeping a separate section for integration, do you mean visually separating the content for this?

My thought would be to put a basic bare-bones Node JWT bcrypt auth implementation in the docs somewhere near where people would be looking (in the same area that the Auth0 and Firebase guides are currently, maybe?).

**Comment by tirumaraiselvan** [comment]
@GavinRay97 What i meant was making an item called `Integration with auth` and taking the already present things (including this issue) into that section (or renaming the current title and moving the non-auth things into a different section). 


Screen Shot 2020-04-17 at 1 36 47 PM

@rikinsk @marionschleifer Thoughts?


Also, as for the current issue, have you seen this PR: https://github.com/hasura/graphql-engine/pull/848

**Comment by marionschleifer** [comment]
@tirumaraiselvan thank you for the input. I'll discuss with @rikinsk in our docs catch-ups.

Meanwhile, @GavinRay97 you can just focus on writing the guide in the file that I created in this PR. We'll take care of the structure in the review 🙂

**Comment by GavinRay97** [comment]
You got it :+1:

**Comment by marionschleifer** [comment]
Closing this, as we'll add this as part of a larger auth docs refactoring PR.

**Pull request closed without merging**
