### PR TITLE
server: lower the isolation level to ReadCommited while inserting/updating invocation logs and events

### PR DESCRIPTION
**Pull request by codingkarthik**
### Description

Earlier, the transaction isolation level for updating a event (scheduled and event trigger) and inserting an invocation log
was set to `RepeatableRead` which is not really necessary because these transactions only have writes in them. This PR changes the level to `ReadCommitted`

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Review by tirumaraiselvan — APPROVED** [review]

**Review by jberryman — APPROVED** [review]
This looks okay to me (and someone should have left a comment if nonrepeatable/phantom reads were a concern). But what was the motivation for this change? Did you find it made things faster?

**Comment by codingkarthik** [comment]
The reason for this change is due to a bug the pro team had faced while using cron triggers, More details are in this internal thread;

https://hasurahq.slack.com/archives/CV3UR1MT2/p1600839874003200

**Comment by jberryman** [comment]
@codingkarthik Cool, some comments should be added at some point if this is an important change (otherwise someone might change it back)

**Comment by codingkarthik** [comment]
@jberryman Sure, I'll add some comments with my next ET/ST PR.

**Pull request merged**
