### PR TITLE
console: fix cron trigger path when containing "/" (close #5935)

### LINKED ISSUE #5935: Bug when creating cron with '/' in name
Cron is created succesfully:
image

But when i click on it, this happens:
image

[EDIT]

Just to being more informative, accessing url at: `http://localhost:9695/console/events/cron/cron%2Fclear-confirmation-codes/modify` manually works.

### PR DESCRIPTION
**Pull request by kentaro84207**
### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

#5935 

### Solution and Design

Apply encodeURIComponent to cron trigger name.
I used encodeURIComponent in the `getServiceEntityLink` function in the `Sidebar.tsx` because using encodeURIComponent for `stName` in the `getSTModifyRoute` function continues to cause a 404 error.

### Steps to test and verify

- Create a Cron trigger with a "/" in the name
- Click the cron trigger link

### CODE REVIEW

**Review by beerose — CHANGES_REQUESTED** [review]
Thanks for your PR!

Would you like to do the same for other kinds of triggers in the switch statement as well?

**Comment by kentaro84207** [comment]
Yes. I'm going to apply it to other types of triggers as well :)

**Review by beerose — APPROVED** [review]
Console

**Review by tirumaraiselvan — APPROVED** [review]
no CL required

**Comment by mehtavishwa30** [comment]
Hello @kentaro84207!

Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2020! We'd love to send you some Hasura swag as a token of appreciation. If you can share your email address, we will send you an email with the swag form shortly. ✨

**Review by beerose — APPROVED** [review]
Console

**Comment by beerose** [comment]
PR was merged (https://github.com/hasura/graphql-engine/commit/e27535e9b9fb8d8f5fb6b2451d31c3a6372282e9)

**Pull request closed without merging**
