### PR TITLE
add analytics

### PR DESCRIPTION
**Pull request by praveenweb**

### CODE REVIEW

**Comment by shahidhk** [comment]
Needs analytics disabling support from server and cli.

**Comment by shahidhk** [comment]
@praveenweb Can we call this variable `disableUsageReporting` and take boolean values for consistency across all configuration? see #60

**Comment by shahidhk** [comment]
@rakeshkky You can push to this branch itself once you're done with server changes

```bash
git remote add praveen git@github.com:praveenweb/graphql-engine.git
git fetch praveen
git merge praveen/console-analytics
git push praveen <your-branch-name>:console-analytics
```

**Comment by coco98** [comment]
@praveenweb We'll have to add an opt-in on the first load of the console metabase style. Can't collect statistics without telling folks first. 
Recommended:
1) Ask users to opt-in, save settings on localstorage
2) For every fresh load of the console, on a new localstorage this warning will repeat
3) Point to docs to ask users to permanently disable by setting an env var

**Comment by shahidhk** [comment]
We are not implementing analytics at this point.

**Pull request closed without merging**
