### PR TITLE
Implemented graceful shutdown for HTTP requests

### PR DESCRIPTION
**Pull request by lorenzo**
### Description

* Listens for SIGINT as the termination signal
* Stops accepting new connections once the signal is received
* Waits for all connections to be drained, before shutting down
* Forcefully kills all pending connections after 30 seconds

Currently this does not send a close message to websocket clients, I'd
like to submit that change as a separate pull request, but at least this
solve my biggest concern which is not getting confirmation for mutations
while restarting the server.

### Affected components 

- Server

### Related Issues
refs #2698 

### Steps to test and verify

I haven't codified this as a test, although I'm happy to provide it if you guide me in running the test suite and your preferred solution. I did this:

Save this to a `test.sh` file
```sh
curl 'http://localhost:8080/v1/graphql' \
-XPOST \
-H 'Content-Type: application/json' \
-H 'Pragma: no-cache' \
-H 'Connection: keep-alive' \
--data-binary $VERY_SLOW_QUERY -v -s > /dev/null
```

Then watched it:

```sh
watch -n 0.8 ./test.sh
```
 
Waited for a few requests to go through then killed the server:

```sh
kill -s INT $PID
```

Verified that no broken socket errors occur, only the final `connection refused`

### Limitations, known bugs & workarounds

This currently does not deal with gracefully shutting down websocket connections

### CODE REVIEW

**Comment by jberryman** [comment]
Thanks for the contribution! The easiest way to run the integration tests is to do 

    $ scripts/dev.sh test

You can also run specific tests with `-k` , e.g.

    $ scripts/dev.sh test -k "test_jsonb_has_all[http]"

The script is very new so do let us know if it works on your machine.

**Comment by lorenzo** [comment]
@jberryman It works on my machine, although I consistently get 2 failures in the master branch.

The test I would need to write requires that I kill the Hasura server, which is handled in the shell file and not in the python test harness. How do you suggest I implement this? The natural way would be to have the start/stop function in the python code and be able to start or stop the server per test if required.

**Comment by jberryman** [comment]
@lorenzo I appreciate you trying out the script.

I think it's not terribly important to have an automated test for this behavior right now, but I'll let @lexi-lambda chime in with her review. The script you've posted is super helpful though thank you! 

Tested locally and change LGTM, didn't look closely at the failure we're getting on CI ^

**Comment by lexi-lambda** [comment]
@lorenzo This looks good to me, but I have one question: given you’re listening on an arbitrary signal, anyway, why not just listen for `SIGTERM` instead of `SIGINT` and remove the Dockerfile change?

**Comment by lorenzo** [comment]
@lexi-lambda I’m fine with that too, just did not want to break backwards compatibility, since the only thing that actually stops the docker container, even before my change, is a SiGINT. I’m fine we removing that line in this PR if you think we should go that way.

**Comment by lorenzo** [comment]
@lexi-lambda I change the signal to `SIGTERM` I could not see a real benefit in using a different one, after all

**Comment by lorenzo** [comment]
@lexi-lambda interesting, what would the advantage of your approach be?

**Comment by lexi-lambda** [comment]
> what would the advantage of your approach be?

Mostly just consistency with what GHC already does. Originally I was thinking it might make it easier to implement graceful shutdown for things running on several different threads, but that isn’t actually true, since GHC only throws `UserInterrupt` to the main thread, anyway. It’s also very slightly simpler to handle both SIGTERM and SIGINT together, since you can just catch either exception. It’s not a big difference, though.

Anyway, it seems like, interestingly enough, these changes make the CLI tests fail! It looks like, for some reason or another, the graceful shutdown on SIGTERM causes the working tree to become dirty when it didn’t before. I am not immediately sure why that is the case.

**Comment by lorenzo** [comment]
@lexi-lambda I think it is trivial with this code to install the same signal handler for SIGINT as well. Do you want me to add thet

**Comment by lexi-lambda** [comment]
If you would like, but there’s no need to.

**Comment by lorenzo** [comment]
@lexi-lambda I used my very limited knowledge on what I thought could be wrong in the tests, but I truly don't know what it is :(

**Comment by lorenzo** [comment]
@lexi-lambda I finally managed to make the test script pass

**Pull request merged**
