### PR TITLE
add liveness and readiness kubernetes probes

### PR DESCRIPTION
**Pull request by fungiboletus**
### Description
[Kubernetes liveness and readiness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/) can be used to know when a kubernetes deployment is ready, and when it is healthy.

[It uses the Hasura `GET` `/healthz` endpoint.](https://hasura.io/docs/latest/api-reference/health/)

### Changelog

__Component__ : server

__Type__: enhancement

__Product__: community-edition

#### Short Changelog

add liveness and readiness kubernetes probes

### Related Issues
NA. I can create an issue if you really need it.

### Solution and Design
I copy pasted standard liveness and readiness magic yaml.

### Steps to test and verify
Deploy hasura on a kubernetes cluster.

### Limitations, known bugs & workarounds
Hasura may be slow to start on extremely slow hardware, and kubernetes may kill hasura before it manages to completely start.

In such case, an `initialDelaySeconds` may be added in the probe. To give Hasura more time to start. I would guess that owner of such bad hardware are already aware of `initialDelaySeconds`, as they probably have to add it to most of their kubernetes deployments. I don't think changing the default value is necessary.

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Review by tirumaraiselvan — APPROVED** [review]

**Comment by tirumaraiselvan** [comment]
@fungiboletus Can you raise the PR to master branch pls?

**Review by tirumaraiselvan — CHANGES_REQUESTED** [review]
This looks good but shouldn't the PR be raised to `master` branch?

**Comment by NoriSte** [comment]
Dumb question: what about rebasing the branch over `master`? ATM the branch includes 22 commits and it needs a review from almost all the Hasura Code Owners... But @fungiboletus **only included one commit** (the first one) and the PR should include only this one. The other 21 commits come from the Hasura engineers but it's confusing that this PR include them, am I wrong?

**Comment by fungiboletus** [comment]
> Dumb question: what about rebasing the branch over `master`? ATM the branch includes 22 commits and it needs a review from almost all the Hasura Code Owners... But @fungiboletus **only included one commit** (the first one) and the PR should include only this one. The other 21 commits come from the Hasura engineers but it's confusing that this PR include them, am I wrong?

Sorry about that. I changed the branch using the Github web interface and I didn't expect to get this mess. I can try to rebase, but maybe I could also close this PR and create a new one. What would you prefer?

**Comment by NoriSte** [comment]
> > Dumb question: what about rebasing the branch over `master`? ATM the branch includes 22 commits and it needs a review from almost all the Hasura Code Owners... But @fungiboletus **only included one commit** (the first one) and the PR should include only this one. The other 21 commits come from the Hasura engineers but it's confusing that this PR include them, am I wrong?
> 
> Sorry about that. I changed the branch using the Github web interface and I didn't expect to get this mess. I can try to rebase, but maybe I could also close this PR and create a new one. What would you prefer?

Go for a new one and link it from this PR by leaving a comment here 😊 Thank you ❤️

**Comment by fungiboletus** [comment]
I created the pull request #9357 🥳

**Pull request closed without merging**
