### PR TITLE
cli: clarify flags on migrate create

### PR DESCRIPTION
**Pull request by tirumaraiselvan**
### Description

Some changes to the description of flags in `hasura migrate create`

- [ ] Server
- [ ] Console
- [x] CLI ( TODO: @scriptonist )
- [x] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### CODE REVIEW

**Comment by tirumaraiselvan** [comment]
oh wow. Cool. @scriptonist will do the cli changes.

**Comment by tirumaraiselvan** [comment]
@scriptonist Instead of doing all these commits to reset, can you just fork a new branch with only cli changes. Also note the change in `sql-from-server` flag.

**Comment by scriptonist** [comment]
@tirumaraiselvan, and create a fresh PR ?

**Comment by tirumaraiselvan** [comment]
Yes. I will close this.

**Pull request closed without merging**
