### PR TITLE
docs: replace react & graphiql imports with a custom directive

### PR DESCRIPTION
**Pull request by sezgi**
### Description

Replace React & GraphiQL JS & CSS imports with custom `graphiql` directive, since we're not using any GraphiQL functionality, only styles.

`Files changed` shows 47 -- this is mostly from removing `:view-only:` attribute.

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### CODE REVIEW

**Comment by marionschleifer** [comment]
@sezgi in the deploy preview, the GraphiQL examples now look like this:

image

They don't have the GraphiQL styles anymore. Was this intended?

**Comment by sezgi** [comment]
@marionschleifer yes, this is intentional. It's using code blocks with `graphql` and `json` highlighting, since the react and graphiql libraries are removed.

**Comment by marionschleifer** [comment]
I'll leave this to @rikinsk. Personally I liked the old GraphiQL style 🙂

**Comment by sezgi** [comment]
@marionschleifer the motivation for this PR is performance, by removing big libraries (React & GraphiQL), as well as tons of unused local code :)

**Comment by sezgi** [comment]
The styles can always be tweaked

**Pull request closed without merging**
