### PR TITLE
Update Digital Ocean docs with caddy bug fix info

### PR DESCRIPTION
**Pull request by tehpsalmist**
### Description
https://caddy.community/t/way-to-cache-ssl-certificate-and-not-reissue-it-every-reload-docker/10385

This issue crops up if you reload the docker-compose file too often. This PR inserts a step in the docs to clarify how to avoid that issue.

### Changelog

__Component__ : docs

__Type__: bugfix

__Product__: community-edition

#### Short Changelog

inserts a step in the Digital Ocean guide for enabling SSL via Caddy.

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

### CODE REVIEW

**Comment by robertjdominguez** [comment]
Thanks for this PR, @tehpsalmist 🚀 

Taking a look at this and getting back to you soon 👍

**Comment by tehpsalmist** [comment]
> Thanks for this PR, @tehpsalmist 🚀 
> 
> 
> 
> Taking a look at this and getting back to you soon 👍 

If you need any insight from me while reviewing, I'm available any time: bstewardcodes@gmail.com

**Comment by shahidhk** [comment]
Hi @tehpsalmist, the volumes are only removed if you use `-v` in docker compose down command, right? Why do we need to explicitly create the volume then? 
Let me know if I am missing something.

**Comment by tehpsalmist** [comment]
> do we need to explicitly create the volume then?

Admittedly, I don't know enough about docker to say that this is an exclusively required step, but I do know that the existing commands and configurations given led to the volume being destroyed every time down/up was run. If you know how to configure the docker compose file so that the volume will persist without manually creating it, then that would also solve the problem. Then we can update the repo that holds the Digital Ocean configuration with that change.

**Comment by mendeni** [comment]
@hasura/infra-tools could someone review this PR when possible?

**Comment by nithindv** [comment]
@tehpsalmist Apologies for the delay. 

We tried to reproduce this but could not do so; it works as expected. The volumes continue to stay intact unless you run a `docker-compose down -v`.

 Could you share a detailed list of commands that we can use to replicate this?

**Comment by Stefmore02** [comment]
I'm closing this PR due to lack of activity. Feel free to re-open if you want to pick it back up.

**Pull request closed without merging**
