### PR TITLE
Sample app node be hasura

### PR DESCRIPTION
**Pull request by razi-ed**
### Description
- add a sample app on integrating Hasura into an existing node BE

### Affected components 
- Docs
- Community/sample-apps

### Related Issues
#316 
#1740 

### Solution and Design
- node BE with Postgres DB
- spin up Hasura Graphql engine on Heroku
- link Postgres DB and GraphQL Engine
- expose an API in node BE with Apollo Server GraphQL middleware
- utilize Http Link to integrate Hasura Graphql engine node BE
- add appropriate README

### Limitations, known bugs & workarounds
- new to Hasura Ecosystem

### CODE REVIEW

**Comment by marionschleifer** [comment]
@razi-ed Thank you so much for your contribution 🙏 I can see it's still a draft PR. Are you still working on this? Whenever you're ready, please convert it to a regular PR and we'll try it out and give it a review 🙂

**Comment by razi-ed** [comment]
> @razi-ed Thank you so much for your contribution  I can see it's still a draft PR. Are you still working on this? Whenever you're ready, please convert it to a regular PR and we'll try it out and give it a review

I have converted draft to review PR :tada:. Please let me know changes needed :art:, if any.

**Comment by razi-ed** [comment]
@marionschleifer Thank you for the feedback. I will find out an optimal solution and will update the PR description with the plan of action and implement them accordingly.

**Comment by marionschleifer** [comment]
@razi-ed just wanted to check in how it is going and if you're still interested to complete this PR 🙂

**Comment by zenflow** [comment]
@razi-ed I encourage you to finish this PR.. really a useful example and right now it's hard to find (here in a PR rather than in `master`)

**Comment by razi-ed** [comment]
@marionschleifer I am still interested in completing the PR.

**Comment by Stefmore02** [comment]
Closing this PR since it has been inactive for quite some time and some features are outdated. Feel free to open a new PR.

**Pull request closed without merging**
