### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ankitkachru**
Fixed grammatical error.

### Description

What component does this PR affect? 

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [x] This change requires a change in the documentation. 
- [x] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by shahidhk** [comment]
Thanks for the PR @ankitkachru. But code is the right word here.

**Comment by ankitkachru** [comment]
@shahidhk : 'are' is used further in the sentence. Source 'code are' under the license ?

**Comment by ankitkachru** [comment]
> Thanks for the PR @ankitkachru. But code is the right word here.

@shahidhk : 'are' is used further in the sentence. Source 'code are' under the license ?
Either we change 'code' to 'codes' or 'are' to 'is'.

**Comment by dsandip** [comment]
@ankitkachru Let's please change the line to:

```markdown
The source code in this directory is available under an [MIT License](../LICENSE-community).
```
Thank you!

**Comment by ankitkachru** [comment]
@dsandip, created PR: #906 with patch-3. #884 can be closed. Hope this is alright.

**Pull request closed without merging**
