### PR TITLE
server: _inc numeric (fix #3573)

### LINKED ISSUE #3573: _inc operator works only for Int fields
In Hasura console I see the following description for _inc opertor: 
> input type for incrementing integer columne

But I read in your blog [here](https://blog.hasura.io/updating-data-using-mutations-on-hasura-graphql-87c7e22503bc/), that it should work for any numeric field. Where is the truth?

### PR DESCRIPTION
**Pull request by abooij**
Add support for `_inc` on `real`, `double`, `numeric` and `money` (fix #3573)

### Description

Previously, the atomic `_inc` operator only supported `smallint`, `integer` and `bigint`. This expands support to other numeric types.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Solution and Design

There are three components to this change:
- Hasura support for the `money` type.
- Advertising `_inc` support on other numeric types.
- Generating an `rhsExpOp` with the type annotation looked up from the update context.

### Steps to test and verify

I have added a test in `server/tests-py/queries/graphql_mutation/update/basic/numerics_inc.yaml`.

### Limitations, known bugs & workarounds

None known

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [x] New GraphQL schema is being generated:
   - [x] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by abooij** [comment]
This currently seems to fail on some git tags testing issue, which I don't know how to resolve because I don't know what it intends to check.

**Comment by perrosnk** [comment]
That's so useful! Thank you @abooij. Hope there is enough time to get merged into v1.2
The more I use Hasura, the more I love it. Well done to everybody!

**Comment by itsanishjain** [comment]
Anyone confirms, I think it is not working yet

**Comment by itsanishjain** [comment]
```
mutation ($userId: String!, $eth: numeric!) {
  update_sellers(where: {user_id: {_eq: $userId}}, _inc: {eth: $eth}) {
    returning {
      user_id
      eth
    }
  }
}


```

Testing this, and get back null

**Pull request merged**
