### PR TITLE
Solved #584 Docs for Deploying graphql on Azure

### PR DESCRIPTION
**Pull request by vnyk**
### Description

What component does this PR affect? 

- [x] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [x] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Docs update
- [x] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [x] This change requires a change in the documentation. 
- [x] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by vnyk** [comment]
But I wrote it in Md only. Pleace check now. I have tried it myself

**Comment by shahidhk** [comment]
Thanks @vnyk. The docs should be in [RestructuredText](http://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html). Not in markdown.

Also, try to follow the style and format other deployment guides have. For example, [Kubernetes](https://github.com/hasura/graphql-engine/blob/master/docs/graphql/manual/deployment/kubernetes/index.rst)

This guide need to be integrated with the existing docs.

**Comment by vnyk** [comment]
Done

**Comment by vnyk** [comment]
Check, final

**Comment by shahidhk** [comment]
@vnyk Thanks for changing the format.

I have some formatting suggestions. But, before that, I cannot find the Postgres settings in the guide. Hasura won't work without a Postgres database. How is t being configured?

**Comment by shahidhk** [comment]
Hello @vnyk, let me know if you are planning to work on this. :smile:

**Comment by shahidhk** [comment]
@vnyk I am closing this pull request. Feel free to open another one when you find time. Thanks for your efforts :smile:

**Pull request closed without merging**
