### PR TITLE
Fixed variable name in TodoPublicList.re from reason-react-apollo sample

### PR DESCRIPTION
**Pull request by RomarQ**
### Description

The correct variable name is `client` and not `c`, now the example will work as intended.

### Affected components 

- Docs
- Community Content

### CODE REVIEW

**Comment by wawhal** [comment]
Hey @RomarQ could you please merge your three PRs into one and submit it as `learn: ReasonML tutorial bug fixes`?

**Comment by RomarQ** [comment]
Sure, will do that once I get home.

**Comment by RomarQ** [comment]
@wawhal Done, check #2642.

**Comment by RomarQ** [comment]
Closing, since I merged all 3 PR's in #2642.

**Pull request closed without merging**
