### PR TITLE
Show datatype next to column names in advanced options when adding triggers

### PR DESCRIPTION
**Pull request by pthm**
### Description

What component does this PR affect? 

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Related Issue

No related issue

### Solution and Design

Small change to show the column datatype in the "Listen columns for update" section of the Advanced Options when creating new triggers.

After going through the process of creating a bulk load of triggers i found myself having to check  columns data types with Postico to ensure I was enabling/disabling the right ones, Showing the datatype here would have been useful as it cuts out some of that workload

screenshot 2018-12-11 at 18 27 52
 
Would have liked to spend more time on how this is displayed as I'm not sure displaying it in-line next to the column name is the best way of showing this data but I am unfamiliar with the CSS stack used in the console so didn't want to play with the style system.

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [ ] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by dsandip** [comment]
@pthm Thank you for the PR! 

@rikinsk @shahidhk From the various screenshots of this page that I've seen, looks like people have more columns that we usually test with ;) and this is a pretty legit issue. However, I am personally not a fan of the way the column types are shown here and would prefer a table to show the name, type along with a checkbox.

**Comment by 0x777** [comment]
@dsandip Let's just get this in? A different UI would require mockups, CSS changes etc. This looks neat and functional.

**Comment by dsandip** [comment]
@0x777 sounds good. Over to you @karthikvt26 for reviewing (_and @shahidhk if you have any comments_).

**Comment by shark-h** [comment]
Hey @pthm !
We'd love to send you some swag, could you please ping me on Discord (Shark#9863) ?

**Pull request merged**
