### PR TITLE
schema permissions summary page on console

### LINKED ISSUE #2636: Form error handling on clone permissions
Making an invalid selection should not allow saving / cloning.
Screenshot 2019-07-30 at 3 21 47 PM

### PR DESCRIPTION
**Pull request by rikinsk**
### Description

This adds a permissions summary page for a PG schema to the console
- show summary of access control for all roles across tables and actions
- allow copy of permissions from one role to others

TODO:
- push permissions state to open appropriate section in permissions page on edit
- Try out a better layout for displaying the 3-dimensional data (roles x tables x actions)

Misc:
- update About page container
- remove inconsistent highlighting of tooltip icons in Add table
- Permissions page
  - highlight actions and roles as headers in table
  - move bulk action selector to end
  - scroll to edit/bulk section on selection
  - show permission edit icon only on hover
  - pre-select table and action in clone section (resolves #2636)
- Sidebars
  - updated icons for remote schema and events in sidebar
  - update function icon colour in data sidebar to match text
  - update routing in data sidebar to use utils

### Affected components 

- Console

### CODE REVIEW

**Comment by coco98** [comment]
I think if we get a link to the "edit permissions" working, then the rest is just styling right? Seems to work pretty well otherwise :)

**Comment by coco98** [comment]
@rikinsk Does the copy button on the clone modal not work?

**Comment by rikinsk** [comment]
@coco98 of course it does! at least it did last time i checked

**Pull request merged**
