### PR TITLE
allow renaming tables/columns (close #79, fix #240)

### LINKED ISSUE #79: support renaming tables, columns and relationships

### LINKED ISSUE #240: schema cache is not updated when new constraint is added to already tracked table (via console sql)

### PR DESCRIPTION
**Pull request by rakeshkky**
1.  Catalog version has been bumped to `1.1`
    - Foreign key constraints on `hdb_permission` and `hdb_relationship` are altered to have `ON UPDATE CASCADE` condition
    - All `hdb_catalog` views moved to `hdb_views`. 
    - `hdb_table_constraint` and `hdb_table_meta` are new views defined
2. Allow renaming tracked table
3. Allow renaming columns in tracked table
4. `processSchemaChanges` renamed to `processCatalogChanges` thus it can only perform changes in `database`. Rebuilding schema cache from `database` after each `run_sql` query

close #79 
fix #240

### CODE REVIEW

**Comment by coco98** [comment]
@rakeshkky @shahidhk Guys. Why is this issue still open?

**Comment by shahidhk** [comment]
There are some constraints in merging these before releasing `v1.0.0` stable. @0x777 can explain.

**Comment by shahidhk** [comment]
@rakeshkky @0x777 Can we close this PR is this is not relevant anymore?

**Comment by shahidhk** [comment]
Closing for further introspection later.

**Pull request closed without merging**
