### PR TITLE
docs: Fix minor grammatical errors in faq.mdx

### PR DESCRIPTION
**Pull request by kVarunkk**
### Description

Fixed some typos/errors in the documentation(faq.mdx)

### Changelog

__Component__ : server / cli / console / build 

__Type__: bugfix / feature / enhancement 

__Product__: community-edition

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by seanparkross** [comment]
Thanks! Accepted. Will merge.

**Comment by kVarunkk** [comment]
Thanks, @seanparkross!

**Comment by kVarunkk** [comment]
Hey @seanparkross, you might want to add the ```hacktoberfest-accepted``` tag on this PR as my hacktoberfest profile shows that Hasura is not a part of it. 
Have a look: 

Hasura

Thanks!

**Comment by kVarunkk** [comment]
I had one more doubt @seanparkross, will I be eligible for swags from Hasura now that my PR has been merged?
Thanks!

**Comment by Stefmore02** [comment]
Hey! @kVarunkk 

We do appreciate your contribution, however, we’re committed to prioritizing quality contributions that address an issue as outlined in our [blog](https://hasura.io/blog/with-hasura-celebrate-open-source-in-style-with-hacktoberfest/). I'm afraid this PR doesn't qualify for the "hacktoberfest-accepted" label.

**Pull request closed without merging**
