### PR TITLE
Create remote-schemas.portuguese.md

### PR DESCRIPTION
**Pull request by fi-carvalho**
Create portuguese translation of the remote schemas doc.

### Affected components 

- Server
- Console
- CLI
- Docs
- Community Content
- Build System
- Tests
- Other (list it)

### CODE REVIEW

**Comment by fi-carvalho** [comment]
Created portuguese translation of the remote schemas

**Comment by marionschleifer** [comment]
@fi-carvalho cool, thanks 🙂 now all that is needed is to add a link to this translation in the English version (https://github.com/hasura/graphql-engine/blob/master/remote-schemas.md) and to this table: https://github.com/hasura/graphql-engine/tree/master/translations.

**Comment by fi-carvalho** [comment]
> @fi-carvalho cool, thanks 🙂 now all that is needed is to add a link to this translation in the English version (https://github.com/hasura/graphql-engine/blob/master/remote-schemas.md) and to this table: https://github.com/hasura/graphql-engine/tree/master/translations.

**Comment by fi-carvalho** [comment]
Done!

**Comment by marionschleifer** [comment]
@fi-carvalho I'm closing this PR. If you would like to implement the above changes, feel free to re-open 🙂

**Pull request closed without merging**
