### PR TITLE
change success code from 200 to 2xx (close #2335)

### LINKED ISSUE #2335: [Event Triggers] HTTP 201 'created' response has negative status icon in logs
If the HTTP response code of a webhook is [201](https://httpstatuses.com/201), it shows a negative red cross icon in the Invocation Logs table.

Perhaps all `HTTP 2xx` status codes should show a positive green check icon?

e.g. first row returned a 200, the second returned a 201

Screenshot 2019-06-05 at 2 24 15 PM

### PR DESCRIPTION
**Pull request by strongSoda**
fix issue #2335 

### Affected components 
- Console

### Related Issues
#2335

### CODE REVIEW

**Comment by rikinsk** [comment]
@strongSoda can you move the testing of status code to a util function and use that everywhere instead of repeating the regex match. Also use a stronger regex. like `2[0-9][0-9]`

**Comment by strongSoda** [comment]
done

**Comment by strongSoda** [comment]
@rikinsk  shall I change the util function name from `verifyStatus`  to more specific `verifySuccessStatus` ?

**Comment by rikinsk** [comment]
@strongSoda `verifySuccessStatus` seems like a better name

**Comment by strongSoda** [comment]
done @rikinsk

**Pull request merged**
