### PR TITLE
add examples to GraphQL API reference operators (fix #3147)

### LINKED ISSUE #3147: Add clarification & examples to operators in docs
We should explain the operators in the API reference: https://docs.hasura.io/1.0/graphql/manual/api-reference/graphql-api/query.html#operator. We should also add an example for each of them.

We can do something similar as with jsonb operators: https://docs.hasura.io/1.0/graphql/manual/queries/query-filters.html#jsonb-operators-contains-has-key-etc and also link to the Postgres docs.

### PR DESCRIPTION
**Pull request by marcotaranta**
### Description
The operators in the GraphQL API reference documentation needed
examples, just like in the Hasura GraphQL engine query filters
documentation.
Resolve answers to everything, fix #3147.

### Affected components 
- Docs

### Related Issues
#3147 

### Solution and Design
New info added to the documentation of the GraphQL API query operators.

### Steps to test and verify
Check the generated documentation HTML.

### CODE REVIEW

**Comment by marcotaranta** [comment]
For some reason the license/cla is signed with my account, but the bot says it isn't.

**Comment by marionschleifer** [comment]
@marcotaranta That's okay, we can fix it manually once we get to review the PR 🙂

**Comment by Stefmore02** [comment]
Thank you for this PR; we are deeply sorry for taking so long to review it. Unfortunately, we'll close it since it's outdated --> `.rst` and the current docs site uses `.mdx`.

**Comment by seanparkross** [comment]
Closing again as these are .rst and not .mdx docs. If you can port them over to .mdx please feel free to open a new PR. We are planning on updating operators references in docs too. 

Thanks
Sean

**Pull request closed without merging**
