### PR TITLE
add python webhook for product-review

### LINKED ISSUE #9910: Create a Python version of our ST Recipe for Product Reviews
## Description ✍️ 

Take this [existing handler](https://hasura.io/docs/latest/scheduled-triggers/recipes/product-review/) written in JavaScript and provide a Python version.

## Acceptance criteria 📋 

- [ ] Use the `<Tabs />` component to create parity with a Python version of the handler already on this page ☝️

### PR DESCRIPTION
**Pull request by ashutuptiwari**
### Changelog

__Component__ : docs 

__Type__: enhancement 

__Product__: community-edition

#### Short Changelog

Created a Python version of our ST Recipe for Product Reviews

### Related Issues
close #9910 

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by robertjdominguez** [comment]
Thanks for this @ashutuptiwari 👍 

A few things:
- The build isn't succeeding. You can test things by following our [contribution guide](https://hasura.io/docs/wiki/contributions/#step-6-test-your-local-changes). Looks like there's a simple syntax error somewhere.
- Additionally, please implement some of the logic like others have added in their [recent contributions](https://github.com/msk4862/graphql-engine/blob/fd1a52bc98a0e0412e06ec77ef2ec5222053c1ea/docs/docs/scheduled-triggers/recipes/check-expiration.mdx#L337-L344) that account for SMTP servers that aren't already configured. This ensures a user can immediately see how the webhook will work locally 🚀

**Comment by ashutuptiwari** [comment]
Alright i'll have look

**Comment by ashutuptiwari** [comment]
@robertjdominguez have a look

**Comment by robertjdominguez** [comment]
Looks great, @ashutuptiwari — thanks for the updates 👍 

I've approved it on our internal repo, and CI should pick this up and merge it soon. Thanks for your contribution 🔥 

cc @Stefmore02

**Comment by ashutuptiwari** [comment]
Thanks @robertjdominguez, always a pleasure to contribute to open source😁😁 . One question
-->when will this issue be added to the hacktoberfest-accepted label?

**Comment by Stefmore02** [comment]
Hey @ashutuptiwari!

Thanks so much for your contribution to Hasura OSS during Hacktoberfest 2023! 🎉 We'd love to send you some Hasura swag as a token of appreciation, please send me an email to [estefani@hasura.io](mailto:estefani@hasura.io) to send you our swag form.✨

**Pull request closed without merging**
