### PR TITLE
 handle cross schema permissions in console permission builder

### PR DESCRIPTION
**Pull request by rikinsk**
### Description

What component does this PR affect? 

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by rikinsk** [comment]
Close #1127

**Comment by praveenweb** [comment]
@arvi3411301 - Can you check why heroku app is not being generated?

**Comment by arvi3411301** [comment]
@praveenweb @rikinsk you need to open the PR from the fork.

**Comment by rikinsk** [comment]
Sorry ppl. I messed setting up this PR. Closing and opening it again.

**Pull request closed without merging**
