### PR TITLE
Load big jsonb value in console (close #5136)

### LINKED ISSUE #5136: Browser freezes when browsing rows containing large JSONB values in console
One of my tables has a jsonb field and size of the JSON (not compressed into binary) typically ranges from 0.2-1.5MB

Loading a single row typically makes the browser unresponsive in Chrome and freezes it altogether in Safari to the point where I have to force-quit

macOS 10.15.4
2.2 GHz 6-Core Intel Core i7

### PR DESCRIPTION
**Pull request by soorajshankar**
### Description

Load big jsonb value in console by showing first 5000 characters on the screen. showing huge value in DOM can freeze the browser.

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components
- [x] Console

### Related Issues
close #5136

### Solution and Design
This PR will trim the raw value before displaying it on the DOM.

### Steps to test and verify
add a table with huge raw data and validate that the first 5000 characters are only displayed on the DOM
 
### Limitations, known bugs & workarounds
We need to think about some other UX (maybe a new tab which opens up raw data) to show the complete data.

### CODE REVIEW

**Comment by tirumaraiselvan** [comment]
Possibly also closes: https://github.com/hasura/graphql-engine/issues/3814

**Comment by soorajshankar** [comment]
@beerose @rikinsk please let me know if you have any other thoughts. 
I think the following can also be considered 
* Adding an option to view raw data on a new tab
* A download option (which is a already in progress)

**Comment by rikinsk** [comment]
Tried this out with large data objects and console still becomes really slow. This doesnt seem to be a DOM rendering issue actually, rather it seems like the amount of data going into the redux state slows down the console. This is happening on the Raw SQL page as well when we fetch large data objects. 
We'll need to figure out a smarter way of dealing with large data going into state too resolve this

**Comment by soorajshankar** [comment]
> Tried this out with large data objects and console still becomes really slow. This doesnt seem to be a DOM rendering issue actually, rather it seems like the amount of data going into the redux state slows down the console. This is happening on the Raw SQL page as well when we fetch large data objects.
> We'll need to figure out a smarter way of dealing with large data going into state to resolve this

@rikinsk the fix can be a combined effect of this PR and [this feature](https://github.com/hasura/graphql-engine/pull/4446) (by this user will be able to choose the columns that they want to query)

This PR will only add an additional layer that protects the console from crashing/ non-responsive behavior by reducing the DOM load.

**Comment by franciscolourenco** [comment]
In my experience the table view in the console is considerably slower than querying the same data via grahpQLi, so it is probably not only about the amount of data.

**Comment by tibotiber** [comment]
Hi team! Just checking, are there any plans to merge this PR? Or is another approach in the works to fix the underlying issue?

**Comment by soorajshankar** [comment]
Thanks folks for all the comments and suggestions, closing this PR for now as we are working on new components on the UI to improve the overall experience (some changes are already gone to latest version)

**Comment by valstu** [comment]
I also have biggish bytea columns which crashes the browser and makes the console ui useless if I need to fix some data on tables. I really hope there would be some quickfix where the data would be truncated or even some query params that would let you disable some columns. 👍

**Pull request closed without merging**
