### PR TITLE
bump stackage version to lts-13

### PR DESCRIPTION
**Pull request by 0x777**
### Description

What component does this PR affect? 

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by shahidhk** [comment]
@ecthiender Some cabal related process is running out of memory. Do we need to rebuild the docker image with the corresponding stack version etc.?

**Comment by ecthiender** [comment]
@shahidhk that is not strictly necessary, but we can try that.

**Comment by ecthiender** [comment]
I have updated the server-builder docker image with latest stack resolver. It still fails with with out of memory error.

**Comment by shahidhk** [comment]
There is a key `resource_class` which can be used to allocate more CPU/RAM for the build. But, this has to be enabled by CircleCI for our account - I have submitted a request for the same.

**Comment by shahidhk** [comment]
Closing in favor of https://github.com/hasura/graphql-engine/pull/1685

**Pull request closed without merging**
