### PR TITLE
Create READMEhindi.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**
make a new readme in different language with cloning readme.md 
### Affected components 

- Server
- Console
- CLI
- Docs
- Community Content
- Build System
- Tests
- Other (list it)

### CODE REVIEW

**Comment by tirumaraiselvan** [comment]
@sakshamtaneja21 Is this WIP? As of now, the translation is not clear and the structure is quite messy.

**Comment by marionschleifer** [comment]
@sakshamtaneja21 some more feedback:
- The file name should be: README.hindi.md
- A link to the file should be added to the English version: https://github.com/hasura/graphql-engine/blob/master/README.md
- Your translation should be added to this table: https://github.com/hasura/graphql-engine/tree/master/translations
Thank you for contributing 🙂

**Comment by sakshamtaneja21** [comment]
hey I have singed the CLA

**Comment by marionschleifer** [comment]
@sakshamtaneja21 thank you. Could you please address @tirumaraiselvan's and my review comments? 🙂

**Comment by sakshamtaneja21** [comment]
sure

**Comment by sakshamtaneja21** [comment]
btw how to be added in 
# github organization member

**Comment by sakshamtaneja21** [comment]
hi

**Comment by marionschleifer** [comment]
@sakshamtaneja21 I'm closing this PR. Feel free to re-open if you would like to implement the suggested changes 🙂

**Pull request closed without merging**
