### PR TITLE
Fix grammatical errors

### PR DESCRIPTION
**Pull request by vinayak42**
Signed-off-by: Vinayak vinayak17122@iiitd.ac.in

### Description

What component does this PR affect? 

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by vinayak42** [comment]
@rikinsk Why would it be "are"? It is saying "each of the columns of the table is". We should associate "is" with "each" since "each" is singular.

**Comment by dsandip** [comment]
@vinayak42 @rikinsk This should work better:

, we have to specify the remote from views. So, when using manual configuration, we have to specify the remote table and how *columns in this table are mapped to the columns of the columns of the remote table*.

**Comment by dsandip** [comment]
@vinayak42 Thank you for your contribution! There's only 1 valid change in your PR, can you please submit a fresh PR for it (look at my previous comment for details). I am going to close this one.

**Comment by vinayak42** [comment]
@dsandip I have submitted another PR #861 with required edits.

**Pull request closed without merging**
