### PR TITLE
Created Vue GraphQL Todo App

### PR DESCRIPTION
**Pull request by Gokul-Ks**
### Description
Built a sample todo app using Vue, GraphQL and Hasura ( for Hacktoberfest contribution )

### Steps to test and verify

Follow the instruction in README.md to test the application

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by Stefmore02** [comment]
Hey, @Gokul-Ks Thanks for this submission! Could you please link the issue number?

**Comment by Gokul-Ks** [comment]
Hi @Stefmore02, unfortunately there is no issue that I can link to this submission. I built a sample app using Hasura and Vue as a community contribution, can this count as a valid contribution?

**Comment by arjunyel** [comment]
@Gokul-Ks Hi friend, thanks for the PR. If we are going to add a Vue sample app I would like you to use:

- Nuxt v3 and Vue v3
- Typescript
- Use GraphQL Code generator with [graphql-typed-document-node](https://github.com/dotansimha/graphql-typed-document-node) and @vue/apollo-composable
- Admin secret shouldn't be in the frontend code, with Nuxt you would only use it server side
- Include the Hasura metadata and migration folder https://hasura.io/docs/latest/migrations-metadata-seeds/index/

**Comment by Stefmore02** [comment]
Hey! @Gokul-Ks 

Here's a friendly reminder to address the changes requested to proceed with this PR 🤓.

**Pull request closed without merging**
