### PR TITLE
add a json path argument to query values inside json columns - hgiasac (close #1598)

### LINKED ISSUE #1598: GraphQL Query JSON?
It'd be really cool if we could declare a field as JSON/B and query it per usual. My reasons for thinking this is that sifting through 50 columns in a table for misc stuff—or having 10 tables all revolving around the same concept—seems messy and hard to navigate.

In contrast, dumping things that are related to a concept, but not big enough to warrant their own table, might clean a db up. For instance, a _User_ might have a _profile_ with some addresses, names, and such in it... A _User_ might also have a bunch of stuff related to _auth_ (e.g. tokens, providers, roles, etc.). If you break those out into their own columns on the _User_ table, you end up with 50 columns. If you break them out to their own tables, you end up stitching together all those tables with relationships.

Open to discussion/suggestions/critique, but the generic query syntax might look like this:

(https://www.db-fiddle.com/f/UsVwfCin7LFLZbAuW691G/2)

```gql
{
  user {
    profile {
      name
    }
  }
}
```

And `where` syntax might look like this:

```gql
{
  user {
    profile(where: {
      addresses: {
        _contains: {
          type: "billing"
        }
      }
    }) {
      name
    }
  }
}
```

So I suppose arrays could do `_contains` where the param is part of an object?

Feel free to poke holes in this. No rush. I'm slightly concerned what performance would be, and if perf is fine, then nailing the syntax might be tricky if there isn't some GraphQL spec for it already.

---

**Resources:**

- https://blog.hasura.io/postgres-json-and-jsonb-type-support-on-graphql-41f586e47536/ (can `where`; can't generic query)
- https://github.com/taion/graphql-type-json (not sure what this is exactly, but it has 200k+ weekly downloads so might be relevant 😅)

### PR DESCRIPTION
**Pull request by dsandip**
### Affected components 

- Server
- Console
- CLI
- Docs
- Community Content
- Build System
- Tests
- Other (list it)

### CODE REVIEW

**Comment by coco98** [comment]
@dsandip I'm not sure if the docs are clear. It's also within the first docs section of simple queries, which makes it more confusing. As a new user looking for how to query stuff, this would be very surprising, it seems like this ought to be more "advanced postgres user" documentation?

Perhaps we should have a separate page for this, or maybe we should include it in the reference documentation? Maybe we should have a page for the different GraphQL types we generate.

Let's also update the JSON blogpost? https://blog.hasura.io/postgres-json-and-jsonb-type-support-on-graphql-41f586e47536/

**Comment by shahidhk** [comment]
@dsandip The commits in this PR are out of sync with master - i.e. some console changes are included. Need to figure out a way to fix that.

**Comment by shahidhk** [comment]
Also, why is this a new PR? What happened to the old one?

**Comment by shahidhk** [comment]
closing in favour of https://github.com/hasura/graphql-engine/pull/1661

**Pull request closed without merging**
