### PR TITLE
docs: open Intercom on feedback & add buttons (close #5264)

### LINKED ISSUE #5264: open Intercom on feedback & add buttons
Per Rajoshi:
- on thumbs down feedback, open Intercom
- add “Edit on GitHub” button next to search bar
- when no search results, show link “Can’t find what you’re looking for?” that opens intercom

### PR DESCRIPTION
**Pull request by sezgi**
### Description
Per Rajoshi:
- on thumbs down feedback, open Intercom
- add “Edit on GitHub” button next to search bar
- when no search results, show link “Can’t find what you’re looking for?” that opens intercom

### Deploy notes
The intercom custom bot for docs (found in the "From Button" section) should be set to live as soon as this ships.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues
#5264

### CODE REVIEW

**Comment by marionschleifer** [comment]
@sezgi when I click on the 👎 icon, this window shows up:

image

Is it somehow possible to customize this? Like can we have a message saying: `Sorry to hear that. Please tell us what you were looking for:`?

Question regarding functionality: if I click 👎 and don't send an Intercom message, is it still stored somewhere? Or do we purposely only want feedback if they fill in the message?

**Comment by sezgi** [comment]
@marionschleifer yes, we initially wanted to show a custom message, but I couldn't find a way (only a way to prepopulate the user’s message). Do you know of a way?

https://developers.intercom.com/installing-intercom/docs/intercom-javascript

Good point on the no-message feedback; I'll fix that case.

**Comment by marionschleifer** [comment]
@sezgi unfortunately I don't know a way to do this either. So is this already discussed with Rajoshi, Rikin etc. that we'll have just the normal Intercom message? 🙂

**Comment by sezgi** [comment]
@marionschleifer please see changes

**Comment by marionschleifer** [comment]
@sezgi now when I click on the preview, immediately the Intercom window opens:

image
image

And it stays open when I navigate through different pages or rather - disappears quickly and opens again when I visit a new page.

Also, Shraddha said on Slack she can help creating a custom message for Intercom 🙌

**Comment by sezgi** [comment]
@marionschleifer I think this has to do with having left it open in your last visit, and will happen with other previews as well. E.g. try with this one (leave intercom open and re-visit): https://github.com/hasura/graphql-engine/pull/5318

**Comment by marionschleifer** [comment]
@sezgi haha yes that is true! Good to know :) I think we're waiting on Shraddha's instructions here right?

**Comment by sezgi** [comment]
Right, this is on hold until Friday-ish.

**Comment by sezgi** [comment]
@marionschleifer @rikinsk please review

**Comment by sezgi** [comment]
@marionschleifer the intercom bot isn't live yet. We can set it to live when this is shipped (ideally immediately after). I'll note this in the description.

**Comment by sezgi** [comment]
@rikinsk this is a quick one, & we can set the intercom custom bot to live when this ships.

**Comment by rikinsk** [comment]
@sezgi I've approved this as @marionschleifer has. But for some reason, hitting the thumbs-down doesnt seem to be opening intercom for me on the preview app

**Comment by marionschleifer** [comment]
@rikinsk I approved because of what @sezgi explained above:

`In this PR, the thumbs down click should result in only a network request and no UI changes.`

**Pull request merged**
