### PR TITLE
Convert function expression to an arrow function

### PR DESCRIPTION
**Pull request by cos**
Just a few cases of converting a traditional function to ES6 arrow functions. Pure refactoring.

### CODE REVIEW

**Comment by cos** [comment]
hm, I'm a bit skeptical of signing a CLA enforced in India -- while enjoyable, that would be quite a bit of travel 😄

**Comment by shahidhk** [comment]
This is an automated tool scanning repos and making PRs with certain linting suggestions. @praveenweb if we want to promote the style of using arrow functions instead on traditional function definition, we should setup linting for the same with existing tools that we use, or setup new tools to do the same.

**Comment by cos** [comment]
@shahidhk it's actually a bit less automated, just because I dislike spam as much as the next person. We are selecting repos by hand, running the tool. and reviewing all fixes before making a PR.

**Comment by shahidhk** [comment]
Thanks @cos.

**Pull request merged**
