### PR TITLE
cli(migrations-image): add support for v2 config (close #3969)

### LINKED ISSUE #3969: update cli-migrations to handle v2 config version

### PR DESCRIPTION
**Pull request by arvi3411301**
### Description
This PR adds support for v2 config in the cli-migrations docker image.

There will be two docker images available for `cli-migrations`:
1. `hasura/graphql-engine:latest.cli-migrations` - This will support the v1 config of CLI.
2. `hasura/graphql-engine:latest.cli-migrations-v2` - This will support the v2 config of CLI which has the `cli-ext` plugin preinstalled.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [x] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues
#3969 

### Solution and Design
Created another docker image `cli-migrations-v2` which adds support for the v2 config of CLI.

### CODE REVIEW

**Comment by shahidhk** [comment]
@arvi3411301 This PR needs docs changes as well -- also, fix the conflict.

**Comment by arvi3411301** [comment]
@shahidhk @rikinsk  This requires docs changes

**Comment by rikinsk** [comment]
A proper entry into changelog needs to be added as well as this is going to be a user workflow change

**Comment by rikinsk** [comment]
@shahidhk @arvi3411301 I've made a note about adding docs for this. I am updating the migrations docs in another PR. Will add it there directly. This PR can be merged without docs.

**Pull request merged**
