### PR TITLE
add json editor for json data type (fix #504)

### LINKED ISSUE #504: JSON Editor for JSON data type in Console UI
We should provide a rich json editor for json data type in console UI.

Pretty JSON output is also nice to have.

### PR DESCRIPTION
**Pull request by Anupam-dagar**
This adds a generic input to json editor toggle component.

Fixes: #504

What component does this PR affect? 

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Solution and Design

simplescreenrecorder20181211

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by Anupam-dagar** [comment]
@shahidhk can you suggest toggle icon for this also?
I found this icon https://fontawesome.com/v4.7.0/icon/code to be relevant.

**Comment by coco98** [comment]
The editor does not show up on edit. It only works for insert.

**Comment by Anupam-dagar** [comment]
@coco98 added editor in edit.

**Comment by mnlbox** [comment]
@Anupam-dagar is it ready? I think it's very useful feature :wink:

**Pull request merged**
