### PR TITLE
refresh the sample app realtime-poll

### PR DESCRIPTION
**Pull request by areski**
### Description
Realtime-poll had some tiny issues but more importantly it was using old version of Apollo, React & GraphQL. I think it was time to do a little refresh on this project.

### Changelog
- [X] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components
- [X] Community Content

### Related Issues
None

### Screenshot
image

### CODE REVIEW

**Comment by marionschleifer** [comment]
@areski thank you so much for your contribution 🙂 could you sign the CLA please?

**Comment by areski** [comment]
Thank you for the great work on Hasura!
CLA signed :+1:

**Comment by areski** [comment]
@marionschleifer any blocker, just asking in case I missed something. Thanks!

**Comment by praveenweb** [comment]
@areski - I have made a commit to remove commented lines. 

@marionschleifer - Looks good to be merged 👍

**Pull request merged**
