### PR TITLE
add java echo boilerplates to aws-lambda event triggers

### PR DESCRIPTION
**Pull request by hexmind**
### Description

Added serverless-triggers/AWS lambda/Java/echo

What component does this PR affect? 

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [x] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Related Issue

#431 

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Docs update
- [x] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [x] I have updated the documentation accordingly.
- [x] I have added required tests.

### CODE REVIEW

**Comment by shahidhk** [comment]
@hexmind CI wont build the community content right now. We are reviewing the PR :smile:

**Comment by hexmind** [comment]
@shahidhk, can you add #hacktoberfest?

**Comment by shahidhk** [comment]
@hexmind Sorry about the delay. This is counted as Hacktoberfest. We're just waiting to hear back on the review.

**Comment by shahidhk** [comment]
Hi @hexmind, really sorry about the delay in getting this merged. If anyone from the community can help in reviewing this PR, we'd greatly appreciate it.

**Comment by marionschleifer** [comment]
@hexmind thank you so much for your contribution and apologies for not reviewing this earlier 🙏 I just tested this out and it works like a charm ✨ 

@shahidhk can you please merge this?

**Comment by marionschleifer** [comment]
@hexmind we would love to ship you some swag for your contribution ❤️ if you are interested, please fill in this form: https://docs.google.com/forms/d/e/1FAIpQLSfLSEmbGqZ0UkRYDdk7Sf6Ry7xeKWG01SJF6Q2DALepPF6pIw/viewform. Looking forward to hearing from you 🙂

**Pull request merged**
