### PR TITLE
add enhancement to search functionality of tables, (close #4321)

### LINKED ISSUE #4321: Enhance Search functionality of tables in Data & Schema Management
The search functionality in the Data & Schema Management of the Hasura seems to filter records considering the _case of letters_ as well.
If this was an intended functionality, it's still better to show the tables which match the filter condition and don't match the letter-case below the tables that match with the exact letter-case.

### PR DESCRIPTION
**Pull request by dinuka-rp**
### Description
Enhance search functionality to filter and display tables which don't match the exact letter-case of the search query.

- The tables that start with the intended search, with the exact letter-case appear firstly.
- The tables that include the intended search, with the exact letter-case appear secondly.
- The tables that start with the intended search, with any letter-case appear thirdly.
- The tables that include the intended search, with any letter-case appear finally.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [x] Console

### Related Issues
#4321

### Solution and Design
Create 2 separate arrays to store tables which start with & include table-names that match any case and append these arrays to the end of the main array that is used to display the search results.

### CODE REVIEW

**Comment by DinDev3** [comment]
I will look into it and try to get it done :)

**Comment by DinDev3** [comment]
@rikinsk Hi! Sorry for taking this long... was stuck with multiple project work at uni.
I tried adding the search enhancement to the Data/ schema section. But, I didn't exactly understand the code there. It was quite different from the Actions search function.
The test seems to fail too.

Is it possible for u to give me any insight on what has gone wrong?

**Comment by beerose** [comment]
Hi @DinDev3!
I see something went wrong while merging master to your branch. Thus it's pretty hard to review your changes and help you out with the solution (as changes are across a couple of commits). Also, there are some conflicts. Could you revert this commit and try to merge the newest master to your branch again?

**Comment by beerose** [comment]
Hi @DinDev3! Just want to ask — do you plan to continue working on this PR?

**Comment by DinDev3** [comment]
Hi @beerose 
Really sorry that I couldn’t attend to this. 
Been a bit packed up with work lately. 
I remember not being able to get search to work in the Data/ Schema section. 

If anyone else is able to fix the issue, I think it’ll be better to allow them to try a fix. 

The reason for the problem with the merge was because I didn’t really know how to merge across forks properly 😅

I’ll be happy to help-out if help is needed :)

**Pull request closed without merging**
