### PR TITLE
Add jsonb to string cast support - postgres (mitigate #6577, #2602)

### PR DESCRIPTION
**Pull request by zifeo**
### Description

Although a more general way of handling deep json filter (https://github.com/hasura/graphql-engine/issues/2468) should also be implemented, this provides the ability to cast jsonb column to text in order to apply full-text operators.

```GraphQL
table(where: {col: {_cast: {String: {_ilike: "%content%"}}}}) {
  col
}
```

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [x] Docs
- [x] Tests

### Related Issues

This will provide a workaround to https://github.com/hasura/graphql-engine/issues/6577 & https://github.com/hasura/graphql-engine/issues/2602, although we might want to keep those issue open for alternative solutions.

### Steps to test and verify

Run the test, and a few queries on a row with col being `{"en": "bbb", "fr": "aaa", as: ["ccc"]}`.

### Limitations, known bugs & workarounds

As stated above, a deep jsonb filter method would be welcome as well, something like:

```graphql
table(where: {col: {_get: {path: "a.b", _eq: "content"}}}) {
  col
}
```

#### GraphQL

- [x] New GraphQL schema is being generated:
   - [x] New types and typenames are correlated
  
#### Breaking changes

- [x] No Breaking changes

### CODE REVIEW

**Comment by dennislaviolette** [comment]
This issue is officially on the short list for backlog review - I will update as we can confirm prioritization.  Thanks so much for you patience.

**Review by rakeshkky — APPROVED** [review]
OSS server LGTM

Please note the conflicts. Thanks.

**Comment by xiaoyu-tamu** [comment]
@zifeo why choose `String`, not `string` or `_string` to keep name consistent ?

**Comment by zifeo** [comment]
@xiaoyu-tamu Pull request was opened 113 days and there must have been a logic at that time, but I cannot remember...

**Comment by xiaoyu-tamu** [comment]
@zifeo Yeah, I just saw this pr got merged while checking changelogs

@rakeshkky 

it would be nice Hasura can keep name consistent if that possible.

The cast operator for type `geography` and `geometry` are snakecase.

https://hasura.io/docs/1.0/graphql/core/queries/query-filters.html#cast-a-field-to-a-different-type-before-filtering-cast

**Comment by rakeshkky** [comment]
@xiaoyu-tamu 
> why choose String, not string or _string to keep name consistent ?

`String` is one of GraphQL [default scalars](https://spec.graphql.org/June2018/#sec-Scalars). 

> The cast operator for type geography and geometry are snakecase.

We also use the same `_cast` operator for `jsonb` to `String` casting. 
`col: {_cast: {String: {_ilike: "%content%"}}}`

**Pull request closed without merging**
