### PR TITLE
rfc: select permission improvements

### PR DESCRIPTION
**Pull request by 0x777**
Rendered:
https://github.com/0x777/graphql-engine/blob/select-permission-improvements/rfcs/columns-in-boolean-expression.md
https://github.com/0x777/graphql-engine/blob/select-permission-improvements/rfcs/disable-query-and-subscription-root-fields.md

### CODE REVIEW

**Comment by aleksander-newstore** [comment]
Thanks for the RFC! I've read through them and the features proposed seem to go a long way to meet our needs.

As I understand it, we'll be able to disable subscriptions altogether, enable querying for some of the entities just via relations and enable/disable the use of certain fields in filter conditions. Thats great!

One scenario that seems to be not covered is multi-field filtering - you need to enable filtering on all the fields from the condition and that means users can filter only on the second or further column in the index.  Eg to use index on order_items_extended_attributes with columns (tenant, order_item_id, name) we would have to enable column name. And in that case someone could make a query filtering just by name which wouldn't use the index.

**Comment by aleksandersumowski** [comment]
Thanks for the RFCs! I've read through them and the features proposed seem to go a long way to meet our needs.

As I understand it, we'll be able to disable subscriptions altogether, enable querying for some of the entities just via relations and enable/disable the use of certain fields in filter conditions. Thats great!

One scenario that seems to be not covered is multi-field filtering - you need to enable filtering on all the fields from the condition and that means users can filter only on the second or further column in the index.  Eg to use index on order_items_extended_attributes with columns (tenant, order_item_id, name) we would have to enable column name. And in that case someone could make a query filtering just by name which wouldn't use the index.

**Comment by marbemac** [comment]
This would also make our permissioning setup so much cleaner (and likely more performant). As of now for our more nested data models, e.g. organization -> project -> things in project, we need to basically repeat all of the org and project permission checks on the tables for things inside of the project. This will be a fantastic change 👍. Any idea on rough timeline post RFC acceptance? Months, quarters?

**Comment by jlowin** [comment]
We currently resort to schema stitching to achieve this; would love to see this feature

**Comment by franciscolourenco** [comment]
Really need this. Any prospects on the implementation of this feature? Thanks!

**Comment by MeisterTea** [comment]
Could the rfc add possibility to disable the where argument https://github.com/hasura/graphql-engine/issues/5751

Is anyone looking into the implementation?

**Comment by mathieutu** [comment]
Hi, this would be a killer feature for us.

However why limit that to query and subscriptions ? I would add the ability to manage the same permissions for mutations too.

**Comment by switz** [comment]
Any plans to implement blocking root level queries? This would be a huge permissioning win.

**Comment by jberryman** [comment]
This sounds good, but may be a fragile or dangerous way to create permissions. For a complex DB schema it may be difficult to see where some data might leak. It should be possible to compute the implicit permissions to show the admin, or even ensure that those don't change if the schema changes.

Just some thoughts

**Comment by marbemac** [comment]
> Any plans to implement blocking root level queries? This would be a huge permissioning win.

👌 this pretty much sums it up - a "simple" (obv I don't really know if it is, but I like to imagine it is :)) option to track a table so that it can be exposed over relations, etc, but not expose it at the root level, would *dramatically* simplify so much of the permissions we have to setup today.

**Comment by Ambro17** [comment]
Is this RFC accepted? Is it on roadmap? I'm trying hasura and really liked it so far, but without this i will be forced to drop it

**Comment by VNadygin** [comment]
Any news on it?

**Comment by PhillipHoffmann** [comment]
This is very much needed.

**Comment by marbemac** [comment]
From how it reads, it seems like release 2.8 might solve this (I have not tried the functionality yet, we're still on 2.1) - specifically https://github.com/hasura/graphql-engine/issues/696. @tirumaraiselvan is that correct?

**Comment by tirumaraiselvan** [comment]
Merged via https://github.com/hasura/graphql-engine-mono/commit/f7f4e60250b4c7375a973d0e5770ac134217767a

**Pull request closed without merging**
