### PR TITLE
persist queries in GraphiQL (closes #1894)

### LINKED ISSUE #1894: console graphiql does not persist queries
Currently, GraphiQL does not persist queries in localStorage. GraphiQL and localStorage must be in sync.

### PR DESCRIPTION
**Pull request by wawhal**
Fix #!894

### Description

Make GraphiQL support persisting queries if there is no `query_file` request param and there are enough tables.

### Affected components 

- Console

### Related Issues

#1894 

### Solution and Design

On GraphiQL load,
1. Check if there is `query_file` in URL parameters. If there is, populate GraphiQL with those queries.
2. If there is no `query_file` parameter, check if there are tracked tables, if there aren't show a message saying "You don't have any tables, go create some from the data section"
3. If there are tables, just use the queries from local storage.

### Steps to test and verify

1. Add a URL parameter like `?query_file=https://raw.githubusercontent.com/wawhal/test-repo/master/queries.graphql`, GraphiQL should template queries from the query file.
2. When there are no tables, GraphiQL should have a comment telling you to go create tables.
3. When there are tables, GraphiQL should load queries from local storage if there are any.

### CODE REVIEW

**Comment by coco98** [comment]
I would like to test this. Please don’t merge till I do.

**Comment by rikinsk** [comment]
@coco98 Can you test this. Let's merge this asap.

**Comment by coco98** [comment]
@rikinsk @wawhal Just tested. LGTM :)

**Pull request merged**
