### PR TITLE
made changes to multiple files

### PR DESCRIPTION
**Pull request by krototype**
### Description

What component does this PR affect? 

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System

Requires changes from other components? If yes, please mark the components:

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System

### Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Docs update
- [ ] Community content

### Checklist:

- [x] I have read the **[contributing guide](https://github.com/hasura/graphql-engine/blob/master/CONTRIBUTING.md)** and my code conforms to the guidelines.
- [ ] This change requires a change in the documentation. 
- [ ] I have updated the documentation accordingly.
- [ ] I have added required tests.

### CODE REVIEW

**Comment by krototype** [comment]
@dsandip I have made the changes as asked for, I want to update the generating code for these auto generated files, so where can I find it?

**Comment by krototype** [comment]
@shahidhk please look into the pull request.

**Comment by shahidhk** [comment]
@krototype Can you merge changes from this PR into this? https://github.com/hasura/graphql-engine/pull/943

**Comment by krototype** [comment]
@shahidhk can you open #943 as there were some problems in this pull request, so I will merge changes of #891 to #943 .

**Comment by shahidhk** [comment]
Sure, please add the changes to #943

**Pull request closed without merging**
