### PR TITLE
Increase idle GC interval to workaround CPU leak issue

### LINKED ISSUE #2565: Hasura using more CPU over time
Hello,

I recently upgraded to hasura 1.0.0.beta.3 and I've noticed that CPU use in the docker container is generally increasing over time, even if no requests are being made to the hasura server.

Here are the logs produced by Hasura (mostly showing nothing is happening):
```
{"timestamp":"2019-07-17T21:51:27.827+0000","level":"info","type":"startup","detail":{"kind":"server_configuration","info":{"live_query_options":{"fallback_options":{"refetch_delay":1000},"multiplexed_options":{"batch_size":100,"refetch_delay":1000}},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"debug","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql"],"enable_telemetry":false,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
{"timestamp":"2019-07-17T21:51:27.827+0000","level":"info","type":"startup","detail":{"kind":"postgres_connection","info":{"database":"postgres","retries":1,"user":"postgres","host":"postgres","port":5432}}}
{"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"postgres\" (172.129.0.3) and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}
{"timestamp":"2019-07-17T21:51:29.951+0000","level":"info","type":"startup","detail":{"kind":"server_configuration","info":{"live_query_options":{"fallback_options":{"refetch_delay":1000},"multiplexed_options":{"batch_size":100,"refetch_delay":1000}},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"debug","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql"],"enable_telemetry":false,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
{"timestamp":"2019-07-17T21:51:29.951+0000","level":"info","type":"startup","detail":{"kind":"postgres_connection","info":{"database":"postgres","retries":1,"user":"postgres","host":"postgres","port":5432}}}
{"internal":"could not connect to server: Connection refused\n\tIs the server running on host \"postgres\" (172.129.0.3) and accepting\n\tTCP/IP connections on port 5432?\n","path":"$","error":"connection error","code":"postgres-error"}
{"timestamp":"2019-07-17T21:51:31.891+0000","level":"info","type":"startup","detail":{"kind":"server_configuration","info":{"live_query_options":{"fallback_options":{"refetch_delay":1000},"multiplexed_options":{"batch_size":100,"refetch_delay":1000}},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"debug","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":null,"stringify_numeric_types":false,"enabled_apis":["metadata","graphql"],"enable_telemetry":false,"enable_console":true,"auth_hook":null,"jwt_secret":null,"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
{"timestamp":"2019-07-17T21:51:31.891+0000","level":"info","type":"startup","detail":{"kind":"postgres_connection","info":{"database":"postgres","retries":1,"user":"postgres","host":"postgres","port":5432}}}
{"timestamp":"2019-07-17T21:51:33.992+0000","level":"info","type":"startup","detail":{"kind":"db_init","info":"successfully initialised"}}
{"timestamp":"2019-07-17T21:51:33.992+0000","level":"info","type":"startup","detail":{"kind":"db_migrate","info":"already at the latest version. current version: \"17\""}}
{"timestamp":"2019-07-17T21:51:33.992+0000","level":"info","type":"startup","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 86","instance_id":"5e7dd705-9331-474a-bda4-986d78801ffa","message":"listener thread started"}}}
{"timestamp":"2019-07-17T21:51:33.992+0000","level":"info","type":"startup","detail":{"kind":"schema-sync","info":{"thread_id":"ThreadId 87","instance_id":"5e7dd705-9331-474a-bda4-986d78801ffa","message":"processor thread started"}}}
{"timestamp":"2019-07-17T21:51:33.992+0000","level":"info","type":"startup","detail":{"kind":"event_triggers","info":"preparing data"}}
{"timestamp":"2019-07-17T21:51:33.992+0000","level":"info","type":"startup","detail":{"kind":"event_triggers","info":"starting workers"}}
{"timestamp":"2019-07-17T21:51:33.992+0000","level":"info","type":"startup","detail":{"kind":"server","info":{"time_taken":2.216395209,"message":"starting API server"}}}
```
Here is a screenshot of a grafana dashboard showing the CPU use over 6 hours:

hasura_cpu_usage

Here is a minimal docker-compose script that can recreate the test environment and the monitoring tools.

[hasura_test.zip](https://github.com/hasura/graphql-engine/files/3404716/hasura_test.zip)

### PR DESCRIPTION
**Pull request by jberryman**
This seems to resolve the issue locally (and has worked in the past),
but it's not clear what exactly is going on here (in particular, why
this should resolve what looks like a memory leak). It certainly seems
like a GHC issue of some sort.

Closes #2565

### CODE REVIEW

**Comment by 0x777** [comment]
Is there any reason why we can't disable idle gc completely?

**Comment by jberryman** [comment]
@0x777 The reason not to (which I forgot when I responded to the ticket at first) is idle GC is necessary to ensure finalizers and deadlocked threads are cleaned up promptly. It could result in some weird behavior or resource leakage with idle GC disabled. It's just hard to anticipate what might go wrong, e.g. what libraries might rely on finalizers running somewhat promptly in all cases. It could be fine but this is more cautious and seems to fix things.

**Comment by jberryman** [comment]
I scaled up the timing intervals for polling threads by the same degree as the proposed fix here (0.3 sec -> 2 sec), and the fix seems to still work. So hopefully the `-I` parameter isn't dependent on polling frequencies (it was never really clear how or if that is related).

**Comment by jberryman** [comment]
@lexi-lambda if you could review when you have the chance ^ :)

**Comment by lexi-lambda** [comment]
Just asking: is there an open GHC issue about this?

**Comment by jberryman** [comment]
@lexi-lambda Nothing I've found where anyone suggests GHC is probably doing something broken. Thanks for asking, a little survey:

The two old tickets I was familiar with and linked elsewhere
https://gitlab.haskell.org/ghc/ghc/issues/3408
https://gitlab.haskell.org/ghc/ghc/issues/4322

A confusing writeup that might have good information but I didn't try to parse:
https://gitlab.haskell.org/ghc/ghc/issues/15402

Two newish tickets that might be exhibiting the issue
https://gitlab.haskell.org/ghc/ghc/issues/11134
https://gitlab.haskell.org/ghc/ghc/issues/13164  (I will see if the simple test case in this one exhibits the issue (i.e. _growing_ cpu/memory) and may comment there)

I wasn't inclined to open a new issue without a small test case, and wasn't real confident creating one would be easy.

**Comment by lexi-lambda** [comment]
Makes sense. [This comment](https://gitlab.haskell.org/ghc/ghc/issues/4322#note_44361) from Simon Marlow is interesting:

> if your application has a timer signal that executes some Haskell code every 1s, say, then you'll get an idle GC after each one. Setting the idle GC to a longer period than your timer signal (e.g. 2s) will prevent this happening.

That seems like it could apply to us, but on its own, it doesn’t get us much further to understanding why that would trigger anything pathological. In any case, this workaround seems harmless.

**Comment by jberryman** [comment]
@lexi-lambda I think you may have to press the button yourself (I'm not authorized to merge, not sure if that's the intention) :-)

**Comment by lexi-lambda** [comment]
I think @0x777 is actually still the only person who can push the button, even though I’ve been marked as the code owner. I think he can also fix that, though.

**Comment by elitan** [comment]
So we wont have to use `- GHCRTS=-I0` anymore?

**Comment by jberryman** [comment]
@elitan that's the idea, but if you can give it a try and confirm it solves the issue for your deployment that would be really helpful!

**Comment by elitan** [comment]
@jberryman Will do!

**Pull request merged**
