### PR TITLE
document postgresql permissions under Amazon RDS

### PR DESCRIPTION
**Pull request by gward**
### Description

Doc fix only. Trying to tie together a lot of incomplete, inconsistent information from around the web.

### Affected components

- [x] Docs

#### Breaking changes

- [x] No Breaking changes

### Limitations, known bugs & workarounds

Did not test for PG 10.

### CODE REVIEW

**Comment by gward** [comment]
Oh, https://github.com/hasura/graphql-engine/issues/1677 is relevant. Not sure this PR _fixes_ that issue, but it makes things a bit better!

**Comment by ecthiender** [comment]
@gward did you not have to grant explicit selects for tables in `information_schema` ? If we have that info as well, then the PR looks complete to me.

**Comment by gward** [comment]
> Did you not have to grant explicit selects for tables in information_schema ?

With PostgreSQL 11: no. The instructions already in the Hasura docs worked for information_schema.

With PostgreSQL 10: it looks like that would be necessary. I did not fully test with PG 10, though, so I am not confident documenting the procedure for PG 10.

**Comment by marionschleifer** [comment]
@gward thank you for your remarks. Would you mind testing this also with Postgres 10 and adding it to the documentation? 🙂

**Comment by tirumaraiselvan** [comment]
Appreciate your contribution and sorry for the delay in getting this through. But this has been superseded by #5228

**Pull request closed without merging**
