### PR TITLE
cli: fix cron triggers not being exported on a metadata export (close #5047)

### LINKED ISSUE #5047: [1.3.0-beta.1] Cron triggers not included in v2-metadata
@tirumaraiselvan 

While testing the cron triggers (or is it scheduled triggers? You have many names for the same thing) I wasn't able to export my test triggers with `hasura md export`, which produces v2 format metadata.

From the Hasura console, the "export metadata" button produces a v1 metadata.json file which does have a `cron_triggers` section.

PS: I made sure to `hasura update-cli --version v1.3.0-beta.1` first

### PR DESCRIPTION
**Pull request by scriptonist**
### Description
Detailed [here](https://github.com/hasura/graphql-engine/issues/5047)

### Affected components

- [x] CLI

### Related Issues
#5047

### CODE REVIEW

**Comment by jflambert** [comment]
I don't see this fix listed in the [1.3.0-beta.2 changelog](https://github.com/hasura/graphql-engine/releases/tag/v1.3.0-beta.2)

**Comment by jflambert** [comment]
@scriptonist I'm trying 1.3.0-beta.2 and it's crashing hard upon loading my 1.2.2 v2 metadata

`time="2020-06-22T02:08:06Z" level=fatal msg="failed to apply metadata: cannot apply metadata on the database: cannot build cron_triggers from metadata: open /tmp/hasura-project/metadata/cron_triggers.yaml: no such file or directory"`

it's fully expecting the file to be present and of course it's not. You should treat it as empty when it's not present or ... I don't know what else, but you will have plenty of people unable to upgrade from 1.2 to 1.3.0

**Comment by scriptonist** [comment]
Hey @jflambert , that's concerning. Just wanted to gather a bit more info.
1. You upgraded your server to `v1.3.0-beta.2`
2. You tried applying metadata (`v1.2.2`) and it failed right?

**Comment by jflambert** [comment]
We can take it here (#5163)

**Comment by scriptonist** [comment]
Cool, cross posting

**Pull request merged**
