### PR TITLE
add About page in console

### PR DESCRIPTION
**Pull request by strongSoda**
### Description
Add an About page under `?`

Display:
- Current server version
- Latest server version available
- Console asset version

### Affected components 

- Console

### CODE REVIEW

**Comment by mnlbox** [comment]
@strongSoda Maybe merge `About` page with `Metadata Status` is better :thinking:

**Comment by mnlbox** [comment]
@strongSoda Maybe merge `About` page with `Metadata Status` is better :thinking:

**Comment by strongSoda** [comment]
@mnlbox  About page is to keep a reference of versions. Metadata status' purpose is to signify whether it's consistent or not without showing I guess.

**Comment by mnlbox** [comment]
@strongSoda for me console asset version not display. Is it finished?
Screenshot from 2019-06-24 08-32-42

**Comment by strongSoda** [comment]
The console part where it's embedded and fetched is finished. The value has to come from the assets cdn.

**Pull request merged**
