### PR TITLE
Fix two minor bugs in the schema cache build process (fix #3759 and #3791)

### LINKED ISSUE #3759: Enum Not Added To Schema
**Problem:**  Enums are not updating v1.1.0-beta.2

**Details/ Steps to Reproduce:**

**New Enum**
1. Change table to enum
   Go to Docs -> no enum found for table

**Change Enum**
1. Add row to existing enum table.
2. Press 'reload enum values'
   Go to Docs -> no additional enum found for table

### PR DESCRIPTION
**Pull request by lexi-lambda**
### Description

This PR fixes cache invalidation for enum values (#3759) and error handling for inconsistent dependent objects (#3791). And since it was necessary to handle propagating cache invalidations across instances as part of this change, this also fixes the inconsistency mentioned in #3792 (but it does *not* address the main point of that issue).

### Affected components
- Server

### Related Issues
#3759, #3791, #3792, #3820

### Solution and Design

  - The schema cache build process tracks any necessary cache invalidations more explicitly and includes them in schema sync events.

  - The schema cache build process takes care to build the GraphQL schema only after pruning dangling dependent objects.

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Breaking changes

  3. Logging

     - [x] Log `JSON` schema has changed (new field in `schema-sync-thread` payloads)

### CODE REVIEW

**Comment by tirumaraiselvan** [comment]
@lexi-lambda How does the behaviour work for syncing now? (as per https://github.com/hasura/graphql-engine/issues/3792#issuecomment-579581067)

For the 2 cases: 

1. When I do `reload_metadata`
2. When I do `reload_remote_schema`

**Comment by lexi-lambda** [comment]
@tirumaraiselvan The cache invalidation is synchronized across instances, so:

  1. When you call `reload_metadata`, it reloads enum values on all instances (but not remote schemas).

  2. When you call `reload_remote_schema`, it reloads that schema on all instances.

**Comment by tirumaraiselvan** [comment]
@lexi-lambda In that case, does this PR supersede this PR: https://github.com/hasura/graphql-engine/pull/3701

**Comment by lexi-lambda** [comment]
@tirumaraiselvan Yes, I believe so, but @rakeshkky should weigh in.

**Pull request merged**
