### PR TITLE
server: fix updating of headers behaviour in the update cron trigger API and create future events immediately

### PR DESCRIPTION
**Pull request by codingkarthik**
Currently, when a cron trigger is updated, the pending events are deleted and the updated cron trigger will be hydrated with new events within a minute. 

This PR fixes that behaviour by creating the pending events immediately after deleting the pending cron events.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by tirumaraiselvan** [comment]
> Oh, also: I think it would be good to include a changelog entry for this, even though it’s minor.

Since this is between beta releases, it's okay to skip this. Especially because the next one is stable (i.e. even if you put a changelog it will be skipped in the actual v1.3.0 stable changelog)

**Comment by codingkarthik** [comment]
It'll be trivial to add a test case, I'll add it now

**Comment by lexi-lambda** [comment]
> (i.e. even if you put a changelog it will be skipped in the actual v1.3.0 stable changelog)

I’m afraid I don’t understand what you mean by this—what do you mean by “skipped,” and why would that happen here?

**Comment by tirumaraiselvan** [comment]
> > (i.e. even if you put a changelog it will be skipped in the actual v1.3.0 stable changelog)
> 
> I’m afraid I don’t understand what you mean by this—what do you mean by “skipped,” and why would that happen here?

Current release is `v1.3.0-beta.2`. Next release is `v1.3.0`. When we write changelog of `v1.3.0`, it would only include all changelog entries from the perspective of v1.2.2 (last stable). Since scheduled triggers didn't exist in v1.2.2, it will only have one entry ("introducing scheduled triggers" in highlight section) and none of these tiny bugfixes/improvements made during beta.

This changelog entry would have been useful if we were releasing `v1.3.0-beta.3` though.

**Comment by lexi-lambda** [comment]
Ah, I see! That makes sense to me, thank you for the explanation.

**Comment by tirumaraiselvan** [comment]
Ofcourse, it's okay if you add a changelog. But since I am following this issue and the next release, I just wanted to point out that it will get dropped.

**Comment by codingkarthik** [comment]
While writing the test, I discovered that there was a bug which did not allow the user to update the `header_conf` of a cron trigger. I have fixed that and added a test for it too.

**Pull request merged**
