### PR TITLE
Add support for pseudo type in computed functions (fix #6175)

### LINKED ISSUE #6175: using 'anyelement' as argument in a hasura function
im trying to implement i18n in my db
i have created a `products` table with `title_id` and a `translations` table with `id`, `lang` and `value`
i have some tables in addition to `products` which have the same column `title_id` so i want to create a function which can accept a generic table as arg
something like this
```
CREATE FUNCTION get_title_translation(item_row anyelement, hasura_session json)
RETURNS TEXT AS $$
  SELECT value
  FROM translations t
  WHERE t.id = item_row.title_id AND t.lang = hasura_session->>'x-hasura-language'
$$ LANGUAGE sql STABLE;
```
The function is created with no problem, but when i add a computed field with this function i get this error:
```
"item_row" argument of the function "get_title_translation" is not COMPOSITE type • "item_row" argument of the function "get_title_translation" of type "pg_catalog.anyelement" is not the table to which the computed field is being added
```
so is there anyway to make this work?

### PR DESCRIPTION
**Pull request by zifeo**
### Description

Add support for pseudo type in computed functions (e.g. anyelement).

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

https://github.com/hasura/graphql-engine/issues/6175

### Solution and Design

Allowlisted pseudo types.

### Steps to test and verify

Play with computed fields and this function.

```sql
CREATE OR REPLACE FUNCTION test(col anyelement, extra int)
RETURNS text
  LANGUAGE sql
  STABLE
AS $function$
   SELECT to_json(col)::text || extra
$function$;
```

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by dennislaviolette** [comment]
This issue is officially on the short list for backlog review - I will update as we can confirm prioritization.  Thanks so much for you patience.

**Comment by zifeo** [comment]
@dennislaviolette Any update?

**Comment by sassela** [comment]
@zifeo thank you for your contribution, the reminder, and for your patience! This one slipped through the net but we're triaging this now (i.e. figuring what, if anything else, we need to merge it). We'll update you here with any questions or progress soon. Thanks again!

**Comment by plcplc** [comment]
Sorry for the wait!

One observation is it's not strictly correct to permit functions that take any pseudo type as argument, as this set is includes types that are not compatible with the table row the graphql engine will be calling the function with.

Also, it's always possible to work around this issue by manually monomorphising a function you would want to use for s computed field by simply defining a wrapper function with the argument specialised to the concrete table row type.

Considering this and that the current type checking implementation is rather complex already we're currently partial to not merge this PR and instead put more effort into documenting the workaround.

@zifeo: Do you know any cases where this workaround is inadequate?

**Comment by zifeo** [comment]
@plcplc I will leave you the internals, I have no memories left of alternatives considered 6 months ago. However as a developper/user, asking for a specialization of function is a no-go. Keeping metadata and sql up-to-date/consistent between environments is already such a pain, I would not add more complexity.

**Comment by plcplc** [comment]
I'm going to close this PR for now, as we'll most likely be developing a potentially very different solution.

> I have no memories left of alternatives considered 6 months ago.

That one is on us - sorry for that.

> Keeping metadata and sql up-to-date/consistent between environments is already such a pain, I would not add more complexity.

Yeah, IIUC, if you maintain more than one environment you would have to apply the workaround for each of them. So I can imagine how being able to use polymorphic function arguments to computed fields might help relieve that some.

> However as a developper/user, asking for a specialization of function is a no-go.

Is this a matter of developers or graphql-engine admins not having write access to the database? Is this something that contributes to managing sql/metadata consistency across multiple environments being a pain?

I think that, even if we're not going to merge this particular PR, getting more context and feedback is super useful for us to better understand and prioritize.

If you'd like to e.g. elaborate in the corresponding issue #6175 on why support for polymorphic function arguments is compelling and the workaround is inadequate that'd be awesome.

**Pull request closed without merging**
