### PR TITLE
docs: fix Auth0 integration instructions (fix #2655)

### LINKED ISSUE #2655: Review and verify guide on Auth0 JWT Integration
Following the instructions [here](https://docs.hasura.io/1.0/graphql/manual/guides/integrations/auth0-jwt.html), I encountered problems when using the suggested URI under the heading **Test auth0 login and generate sample JWTs for testing**.  Two things: first, if you want to use the **/login** endpoint you have to substitute 

> response_type=token

 with 

> response_type=token id_token

Second, for the **/login** endpoint to work, as given in these instructions, you have to disable **OIDC Compliance** under the Auth0 application you are targeting, found under **Applications** > **\<your-hasura-application\>** > **Settings** > **Advanced Settings** > **OAuth**.  If you don't do this Auth0 will give an error after you submit the login form: 

> access_denied: Password login via OIDC-conformant clients with externally-hosted login pages is unsupported

I am a beginner at all of this.  It may be that these instructions worked before Auth0 disabled "as many legacy features as possible".  I quote from [auth0 docs](https://auth0.com/docs/api-auth/tutorials/adoption/oidc-conformant).  I hope this is useful info.

### PR DESCRIPTION
**Pull request by phylor**
### Description
The current documentation for the Auth0 integration is incorrect. Users are not able to connect Auth0 and Hasura.

### Affected components 

- Docs

### Related Issues

#2655

### Solution and Design

Adding the Hasura claims to the `idToken` no longer works. Auth0 only returns a JWT for access tokens. It is hence required to create an API within Auth0 and use its access token to communicate with Hasura.

### CODE REVIEW

**Comment by marionschleifer** [comment]
@phylor Hey Serge 😃 thank you for your contribution! Could you please send an email to marion@hasura.io, so that we can arrange the shipping of your swag?

**Comment by marionschleifer** [comment]
@phylor we have updated our docs with this PR: https://github.com/hasura/graphql-engine/pull/3367. Closing this one. Thank you for your contribution 🙏

**Comment by phylor** [comment]
@marionschleifer Note that you are still missing the creation of the API. Prove me wrong, but I think your docs are still not complete and beginners still won't be able to follow your tutorial to successfully connect Hasura with Auth0.

**Comment by praveenweb** [comment]
@phylor - Hi, you are right in that the docs is missing the API creation step. Reopening this PR now. Will update this with some more instructions before we get it merged.

**Pull request merged**
