### PR TITLE
Adding detail about marking init migrations as applied to the migrations basics docs (closes #4887)

### LINKED ISSUE #4887: Initialising migrations does not mark the generated migration as present in the database
I followed the quick start docs and set up Hasura on Heroku. I added my tables via the console, but now I'm in a position where I want to set up local Hasura, staging, prod etc.

I Initialised migrations and exported migrations and metadata from my Heroku instance. I then applied the generated migration and metadata to Hasura running in Docker.

My local instance then worked identically to my Heroku instance.

I then used `hasura console` to open the console and created some indexes in my Docker instance. A new migration was created successfully, but when I tried to apply the new migration to the original Heroku instance it failed because it tried to re-apply the initial migration recreate tables that already existed.

This seems to be one of two issues:
1. Exporting an initial migration from a database created using the console does not mark that migration as run in Hasura.
2. The generated migrations are not idempotent e.g. Hasura uses `CREATE TABLE` instead of `CREATE TABLE IF NOT EXISTS`.

Is there a way to manually mark a migration as applied for a given Hasura instance?

Should I manually edit my initial migration so that it is idempotent?

Or should I just delete my Heroku instance, create a new one and apply the migrations to an empty database?

### PR DESCRIPTION
**Pull request by RapidOwl**
### Description

When updating my Hasura-driven application to use migrations, it wasn't immediately clear to me how I could re-apply new migrations to the Hasura instance that I'd used to generate my initial migrations (the migrations failed because tables already existed). I think it would be valuable for this information to be present in the Hasura migration basics doc.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [x] Docs

### Related Issues

#4887 

### Solution and Design

I added some extra information to the docs.

### Steps to test and verify

Have a look at the migrations basics section of the docs and confirm that it looks okay.

### Limitations, known bugs & workarounds

N/A

### Server checklist

N/A

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

N/A

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Comment by sruda** [comment]
Some news about it?, I think this is so important because I have had headaches about the f*cking error: `function "set_current_timestamp_updated_at" already exists with same argument types`

**Comment by marionschleifer** [comment]
@RapidOwl thank you for your contribution 🙏  We have a PR open that adds the steps of setting up migrations: https://github.com/hasura/graphql-engine/pull/4898. We leave this PR open for now and see when the other one is merged. cc @sruda

**Comment by RapidOwl** [comment]
Awesome! Thank you.

**Comment by marionschleifer** [comment]
@RapidOwl @sruda this docs page has now been added and includes the step of marking migrations as applied [here](https://hasura.io/docs/1.0/graphql/manual/migrations/migrations-setup.html#step-3-initialize-the-migrations-and-metadata-as-per-your-current-state).

**Comment by RapidOwl** [comment]
Awesome. Thanks for letting me know!

**Comment by sruda** [comment]
@marionschleifer thank you!

**Pull request closed without merging**
