### PR TITLE
graphql2chartjs: fix mapping of non-array types

### PR DESCRIPTION
**Pull request by iamvo**
### Description

The tool tries to map over all available data, breaking it when there is non-array data available. E.g. ID or __typename

### Affected components 

- Community Content

### Solution and Design

Added a check for array types before mapping the data

### CODE REVIEW

**Comment by iamvo** [comment]
Thanks for all the great work your team is doing.

Do you need anything from me to get this through?

**Comment by shahidhk** [comment]
Sorry about the delay @iamvo. @wawhal will review the PR and get back to you.

**Comment by iamvo** [comment]
Do you have a hint on how I npm install this specific version for my application? Or do I just wait for you to bump the version and release on the npm repo?

Sorry if this is the wrong place to ask this question.

**Comment by shahidhk** [comment]
@miqvo Sorry about the delay.
@wawhal Make a release for graphql2chartjs?

**Comment by wawhal** [comment]
These changes are released in [graphql2chartjs v0.3.0](https://www.npmjs.com/package/graphql2chartjs/v/0.3.0).
@miqvo thanks for the contribution :)

**Comment by miqvo** [comment]
Hey @shark-h 

I sent an email.

**Comment by miqvo** [comment]
@wawhal I just tried the new version. It seems like it hasn't been built correctly. The NPM package only contains the test files.

**Comment by wawhal** [comment]
@miqvo it has been fixed. You can check out version 0.3.1
The bundling had failed earlier.
Thanks for reporting.

**Pull request merged**
