### PR TITLE
Project Dolphin: MySQL support

### PR DESCRIPTION
**Pull request by nicuveo**
We've started work on adding MySQL support in graphql-engine (finally!). We've put together this PR so that you can track progress and provide feedback as we work. 

Some of the challenges around query generation
1. Lack of `ORDER BY` support in `json_arrayagg` function in MySQL. 
2. Lack of 'lateral join' support in versions earlier than `8.0.14`.

## Status
Currently, graphql-engine can take a MySQL (> 8.0.14) endpoint and serves a GraphQL API (only queries) which is similar to what is exposed for Postgres. You can't yet use the console to manage this API but this support should land very soon. You can try it out as follows:
```bash
docker run -p 8080:8080 hasura/graphql-engine:pull5655-633f084f /bin/graphql-engine --database-url=<postgres-url-for-metadata> serve --enable-telemetry false --enable-console --mysql-host <mysql-host> --mysql-user <myql-user> --mysql-port=<mysql-port> --mysql-dbname=<mysql-db-name> --mysql-password=<mysql-db-passsword>
```
Note that graphql-engine still needs a Postgres database to store its metadata. 

## Work in progress
- [ ] Dynamically adding MySQL sources through console
- [ ] Integration with the metadata system (relationships, permissions etc)
- [ ] Support for wide range of MySQL versions through a data-loader approach

### CODE REVIEW

**Comment by niekcandaele** [comment]
Hey this is super cool. I've been playing around with this for a wordpress database and it's been really great. 
I have one issue though, I created a discussion about it but haven't had any luck yet. Hope it's okay to crosspost into this PR.
https://github.com/hasura/graphql-engine/discussions/6294

**Comment by everythings-gonna-be-alright** [comment]
web ui:
login:1 Uncaught (in promise) {path: "$", error: "x-hasura-admin-secret/x-hasura-access-key required, but not found", code: "access-denied"}

**Comment by avaitla** [comment]
How are things going? Happy to help test!

**Comment by pankajagarwal** [comment]
@nicuveo are the limitation or work in progress stuff limited to older MySQL versions ? I added the preview with our MySQL DB which is current and i am seeing query, mutations and subscriptions in schema browser on the tables that exist.

Please confirm.

**Comment by codek** [comment]
Has this ground to a halt?  All that work and not yet accepted?

**Comment by alanosman** [comment]
Should this be mysql not postgres? :-)
image

**Comment by miradnan** [comment]
any updates on this?

**Comment by nicuveo** [comment]
Hey everyone! Sorry for the lack of updates: this branch was **exploratory work**; it will not be merged into the engine, and it has been abandoned for a long while... But the good news is that, since then, we've taken the lessons from that work and added support for other databases, such as MSSQL and Citus. MySQL is not officially out yet, but there's [a preview](https://hasura.io/docs/latest/graphql/core/guides/mysql-preview.html#mysql-preview) you can try!

**Comment by pankajagarwal** [comment]
@nicuveo this is the PR for the preview link you shared above. Is it possible to get preview image with version 2 instead ?

**Comment by ya-watanabe** [comment]
I'm really looking forward to the support of m1

**Comment by corysimmons** [comment]
I couldn't care less about MySQL but I desperately want to use Hasura + Planetscale, and Planetscale won't budge off MySQL. 😭

**Comment by Marcisbee** [comment]
> I couldn't care less about MySQL but I desperately want to use Hasura + Planetscale, and Planetscale won't budge off MySQL. 😭

Yes, this is the reason I subscribed to this PR..

**Pull request closed without merging**
