### PR TITLE
[RFC] cli: remove config.yaml

### PR DESCRIPTION
**Pull request by ShraddhaAg**
### Description

RFC for removing `config.yaml` from cli. Read at https://github.com/ShraddhaAg/graphql-engine/blob/rfc-remove-config.yaml/rfcs/remove-config-file.md
### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR.

### Affected components

- [X] RFC

### Related Issues

#1558 and #4561

### CODE REVIEW

**Comment by scriptonist** [comment]
I'm listing down my initial thoughts here and expect this to have many rough edges.

## Objectives
1. Make `config.yaml` optional for running CLI
    - If a user is running the command outside a project directory and providing all the required configuration values via flags or environment variables things should just work.
2. All v1.x projects should maintain the same behaviour AKA to be backward compatible.
    - The behaviour of CLI inside a project should not change in any of the 1.x CLI's. 
       ie things like running a Hasura command from anywhere inside a project directory should continue to work.

Respecting Objective 2, we may not have the liberty to discontinue using a config file, rather make it optional. Therefore I feel our solution should be a combination of everything @ShraddhaAg suggested.

## Use cases
The use cases that we want to satisfy are
### Use case 1
A user expecting Hasura commands to work the same as in the past and likes having a project directory setup.


### Use case 2
A user who doesn't want populate a config.yaml file just to do simple tasks [like opening a console](https://github.com/hasura/graphql-engine/issues/1558)

Even though this is a simple task, the CLI needs to know the locations to which migrations and metadata files are to be saved.
    
### Use case 3
A user with a config V2 project who'll not have a project directory as such, they will have a configuration file with all the necessary values filled in. This use case is only applicable to a config v2 since config v1 enforces a project structure.

### Rough Solution

##### Satisfying use case 1 and 2
`hasura migrate apply`

https://docs.google.com/drawings/d/1WmR6z4WSgk-dRFlZNrAdPutwWcTldkmDXVVsXrJEox4/edit?usp=sharing

##### Satisying use case 3
`hasura migrate apply --config-file /some/path`

https://docs.google.com/drawings/d/1zWCD7Un6qLgfs1r6zNQ6I-f6g6SWwboJyDdQuQSJaVU/edit?usp=sharing

I was thinking out loud here, so please feel free to point out any mistakes.

**Comment by shahidhk** [comment]
I agree with @scriptonist. This looks good. @arvi3411301 Will you take a look too?

**Comment by arvi3411301** [comment]
@shahidhk which config version we would assume if the config file is not found in case of use case 1. Currently cli assumes config version to be 1 in case version field is not found.

Other than that everything seems to be fine for me. 👍

**Comment by scriptonist** [comment]
Whenever a config file is not in the picture I was thinking we assume Config V2, do you foresee any issues from this @arvi3411301

**Comment by arvi3411301** [comment]
@scriptonist We need to inform the user about the default config version, otherwise user who is in config version `1` may end up corrupting his project directory since migrations and metadata are handled differently from config version `2`

cc @shahidhk

**Comment by scriptonist** [comment]
@arvi3411301 I agree with you that we should explicitly let the user know what config version the CLI is using.

[If we cannot find a config file then it means -- we were not able find a project directory](https://docs.google.com/drawings/d/1WmR6z4WSgk-dRFlZNrAdPutwWcTldkmDXVVsXrJEox4/edit)
Then, what we'll do is get all config values from flags and env vars. This should be according to Config V2 since we have a strict requirement of a project directory for Config V1.

But I agree we have to be explicit in docs, command help, logs etc about the config version used in each case.

**Comment by Stefmore02** [comment]
Closing this PR as it's outdated. Feel free to re-open if you consider otherwise.

**Pull request closed without merging**
