### PR TITLE
[WIP] ra-data-hasura multi schema (close #1729)

### LINKED ISSUE #1729: add support for multiple postgres schemas in ra-data-hasura
Currently `ra-data-hasura` assumes the schema to be public. It can accept an optional parameter for schema name, just like headers/httpClient.

### PR DESCRIPTION
**Pull request by mnlbox**
### Affected components 

- Community Content

### Related Issues

#1729 

### Limitations, known bugs & workarounds

@praveenweb Please join me and help me to complete this PR.

### CODE REVIEW

**Comment by mnlbox** [comment]
Guys now I just add hard coded schema property. I don't now how we can pass schema name from react-admin to this adapter. I need your help brow :wink:

**Comment by coco98** [comment]
@mnlbox Thanks for starting this effort ❤️ 
@praveenweb 

Broadly, the user will pass the schema name from the UI to some variable and then that goes into all the queries. What's the right way of doing this for a ra-admin adapter?

**Comment by mnlbox** [comment]
@praveenweb ping

**Comment by praveenweb** [comment]
@mnlbox - Thanks for starting this. Will update the PR with a sample implementation and will give an example on how it would be to consume it.

**Comment by praveenweb** [comment]
@mnlbox - Hi, i have created a PR with a fix and released a new version to support it.

Refer this PR #2068 

Closing this in favor of that.

**Pull request closed without merging**
