### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by wanderer163**
### Changelog

__Component__ : server / cli / console / build 

__Type__: bugfix / feature / enhancement 

__Product__: community-edition

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

### CODE REVIEW

**Review by marionschleifer — APPROVED** [review]
Docs

**Comment by marionschleifer** [comment]
@NoriSte @sassela I reviewed the docs part of this. Would you verify the console and server part respectively? Thank you 🙂

**Review by NoriSte — APPROVED** [review]
The Console-related change is ok, thanks for fixing it 😊

**Comment by wanderer163** [comment]
Hi there, is this PR eligible to apply for Hacktoberfest swag? I couldn't find any link to order.

**Comment by Stefmore02** [comment]
Hey @wanderer163!

We do appreciate your contribution, however, we’re committed to prioritizing quality contributions that address an issue as outlined in our [blog](https://hasura.io/blog/with-hasura-celebrate-open-source-in-style-with-hacktoberfest/). I'm afraid this PR doesn't qualify for the "hacktoberfest-accepted" label.

**Pull request closed without merging**
